feat(DatePicker): add addtional controls to datepicker / dateTime
consta-design-system/uikit pull request #1882
Opened 2021-12-27 13:59 UTC by N1MBER

closes #1692

Добавлено свойство renderAdditionalControls для отрисовки дополнительных контролов

2021-12-29 11:55 UTC, arhayka requested changes

2021-12-29 11:55 UTC, arhayka commented on src/components/DatePickerCanary/__stories__/DatePicker.docs.mdx
> +Чтобы добавить контролы в поле выбора дат нужно указать в свойсво `renderAdditionalControls`
Чтобы добавить контролы в поле выбора дат, нужно указать в свойстве `renderAdditionalControls`
рендер-функцию для отрисовки элементов.

2021-12-29 15:22 UTC, gizeasy requested changes

2021-12-29 15:22 UTC, gizeasy commented on src/components/DatePickerCanary/helpers.ts
> +    renderAdditionalControls?: () => React.ReactNode | React.ReactNode[];
кажется тип функцией тут лишний
ничего не изменится если мы оставим просто `React.ReactNode | React.ReactNode[];` если захотим использовать внутреннее состояние контрола то сделаем возможность прокинуть и функцию

2021-12-29 15:22 UTC, gizeasy commented on src/components/DateTimeCanary/DateTimeCanary.tsx
> +      {renderAdditionalControls && (
вообще лишнее добавлять это в `DateTime` с таким же успехом можем добавить контролы вне компонента
добавь эту возможность только в `DatePicker`

2022-01-11 08:08 UTC, N1MBER commented on src/components/DateTimeCanary/DateTimeCanary.tsx
> +      {renderAdditionalControls && (
**👌**

2022-01-12 08:02 UTC, gizeasy requested changes

2022-01-12 08:02 UTC, gizeasy commented on src/components/DatePickerCanary/DatePickerDropdown/DatePickerDropdown.css
> +  &-Controls {
Видимо придется все таки добавлять рендер контрол в `DateTime` во все виды календаря

2022-01-19 10:05 UTC, gizeasy requested changes

2022-01-19 15:24 UTC, gizeasy requested changes

2022-01-24 13:11 UTC, merged