feat(SnackBar): add progress line timer
consta-design-system/uikit pull request #1978
Opened 2022-01-21 11:28 UTC by N1MBER

closes #1821

Добавлен вид линейного таймера в SnackBar

2022-01-25 15:17 UTC, gizeasy requested changes

2022-01-25 15:17 UTC, gizeasy commented on src/components/SnackBar/Item/SnackBar-Item.css
> +  &-ProgressLine {
Кажется пришла пора отрефачить CSS в этом компоненте
Компонент разрабатывался до сотавления [правил](https://consta-uikit.vercel.app/?path=/docs/%D1%81ommon-file-structure-components--page)

Давай приведем его в порядок:
1) Все дочерние компоненты это отделный БЭМ блоки, соотведственно имеют свой цсс файлик где описаны правился толко для него
2) Если блок исползуется в другом блоке и описаны стили позиционирования, то эти стили описываются в блоке родителе

2022-01-25 15:17 UTC, gizeasy commented on src/components/SnackBar/Item/SnackBar-Item.css
> +      &_progress-line {
вроде по  коду везде `_showProgress_line`

2022-01-25 15:17 UTC, gizeasy commented on src/components/SnackBar/Item/SnackBar-Item.css
> +@keyframes Progress-Line {
`@keyframes ProgressLine-Animation`

2022-01-25 15:17 UTC, gizeasy commented on src/components/SnackBar/Item/SnackBar-Item.css
> +  0% {
Давай трансформом двигать?

2022-01-25 15:17 UTC, gizeasy commented on src/components/SnackBar/Item/SnackBar-Item.css
> +  }
В реализации не учтен момент что при наведении курсором мыши на `Item` его автозакрытие преостанавливается.

2022-01-26 12:11 UTC, N1MBER commented on src/components/SnackBar/Item/SnackBar-Item.css
> +  }
Fixed

2022-01-26 15:07 UTC, gizeasy requested changes

2022-01-26 15:07 UTC, gizeasy commented on src/components/SnackBar/SnackBarItem/SnackBarItem.css
> +  &_animate {
Анимация не относится к этому блоку, перенеси ее в SnackBar-Item

2022-01-26 15:07 UTC, gizeasy commented on src/components/SnackBar/SnackBar.tsx
> +export const cnSnackBarItem = cn('SnackBarItem');
`cnSnackBarItem` остав в блоке `SnackBarItem`
ели ест необходимость доопределить стилей для блока в другом блоке то выражай дочерний блок через элемент родителского

тоесть берешь `SnackBarItem` и в нутри блока `SnackBar` он у тебя `SnackBar-Item`

2022-01-26 15:07 UTC, gizeasy commented on src/components/SnackBar/SnackBar.tsx
>  const cssTransitionClassNames = cnForCssTransition(cnSnackBarItem);
cnForCssTransition(cnSnackBar, 'Item'); таким образом создадутся классы для элемента item

2022-01-26 15:07 UTC, gizeasy commented on src/components/SnackBar/SnackBarActionButton/SnackBarActionButton.tsx
>        {actions.map((item, i) => (
`i` -> `index`

2022-01-26 15:07 UTC, gizeasy commented on src/components/SnackBar/SnackBarLine/SnackBarLine.css
> +  position: absolute;
Сама линия не знает того где она применяется, все позиционирование выноси

2022-01-26 15:13 UTC, gizeasy commented on src/components/SnackBar/Item/SnackBar-Item.css
> +  }
@N1MBER теперь по другому) но тоже не верно, нужно останавливать полосочку при наведении а чейчас она исчезает, посмотри как в таймере, он останавливается и откатывается до ровной секунды. Там раз в секунду обнаявляется компонент с новой позицией заполнения кружечка, с линией надо сделать тоже самое

2022-02-01 10:31 UTC, gizeasy requested changes

2022-02-01 10:31 UTC, gizeasy commented on src/components/SnackBar/SnackBarLine/SnackBarLine.tsx
> +import './SnackBarLine.css';
Анимация не верно себя ведет, при наведении таймер должен приостанавливатся а не исчезать
https://disk.yandex.ru/i/nFg5NraCqqEukg

2022-02-01 10:31 UTC, gizeasy commented on src/components/SnackBar/SnackBarLine/SnackBarLine.css
> +    transition: left var(--progress-line-time) linear;
Постарайся анимировать trasnsform а не left, таким образом общет анимации будет на GPU

2022-02-02 07:15 UTC, merged