feat(TextField): add new type for autoComplete on TextFiedl
consta-design-system/uikit pull request #1994
Opened 2022-01-27 13:14 UTC by N1MBER

closes #1985

Изменен тип свойства `autoComplete` для TextField.

2022-02-01 10:44 UTC, gizeasy requested changes

2022-02-01 10:44 UTC, gizeasy commented on src/components/TextField/helpers.ts
> +    autoComplete?: AutoCompete;
добавь еще `string` и проверь работают ли подсказки после этого.
когда создавали `type KeyCode` удалось сделать так чтоб и подсказки работали и можно было любую строку указать

2022-02-01 13:02 UTC, N1MBER commented on src/components/TextField/helpers.ts
> +    autoComplete?: AutoCompete;
Я изначально делал с `string`,  но так подсказки вообще не работали, пытался также сделать как и в `KeyCode`, однако та же песня, по факту  мы перечислили все возможные для автокомплита значения

2022-02-01 13:04 UTC, gizeasy commented on src/components/TextField/helpers.ts
> +    autoComplete?: AutoCompete;
А в KeyCode оно работает, посмотри в хуке

2022-02-02 07:05 UTC, gizeasy approved these changes

2022-02-02 07:05 UTC, merged