refactor(SnackBar): add other props for detecting item props and also update doc
consta-design-system/uikit pull request #2032
Opened 2022-02-04 16:20 UTC by N1MBER

closes #1011

Отрефакторен компонент, добавлена возможность указывать `items` любого типа, также поправлена документация

2022-02-09 08:34 UTC, gizeasy requested changes

2022-02-09 08:34 UTC, gizeasy commented on src/components/SnackBar/SnackBar.tsx
> +export type Item = {
Просили сделать имя в домене 

давай `SnackBarItemDefault`

2022-02-09 08:34 UTC, gizeasy commented on src/components/SnackBar/SnackBar.tsx
> +  key: string | number;
`key: string | number;`
как счиаешь осавить так или считать по дефолту 
`key: string` но в гетере разрешить `string | number` и геттер не обязаельный пока `key: string | number`

ну ем самым мы более строго описываем тип по умолчанию но ползоваель может всегда воспользоваься своим и там уже использовать `key: string | number`

2022-02-09 08:34 UTC, gizeasy commented on src/components/SnackBar/SnackBar.tsx
> +  message?: string | number | React.ReactNode;
React.ReactNode буде досаточно

2022-02-09 08:34 UTC, gizeasy commented on src/components/SnackBar/SnackBar.tsx
>  export const SnackBar: React.FC<SnackBarProps> = (props) => {
нужно добавить дженериков на компонент иначе от геттеров ни какой пользы нет

2022-02-09 08:34 UTC, gizeasy commented on src/components/SnackBar/SnackBar.tsx
> +              {...itemProps}
кажется что сам item может обойтись и без геттеров, пускай уже готовые параметры получает

2022-02-09 08:34 UTC, gizeasy commented on src/components/SnackBar/__stories__/SnackBar.docs.mdx
> +  return <SnackBar items={items} getItemIcon={(item) => item.icon} />;
сделай пример иконки в зависимости от сатуса

2022-02-09 08:34 UTC, gizeasy commented on src/components/SnackBar/__stories__/SnackBar.docs.mdx
> +  return <SnackBar items={items} getItemStatus={(item) => item.status} />;
по умолчанию статус находися в `item.status` пример с геттером должен неси практическую выгоду, к примеру item содержит поле `criticality` с типом `1,2,3` и геттер переводит уже в наш формат

2022-02-09 08:34 UTC, gizeasy commented on src/components/SnackBar/__stories__/SnackBar.docs.mdx
> +  return <SnackBar items={items} getItemActions={(item) => item.actions} />;
кнопка в зависимоси от `item.url` типа если есть ссылка то кнопку показываем

2022-02-09 08:34 UTC, gizeasy commented on src/components/SnackBar/__stories__/SnackBar.docs.mdx
> +      <SnackBar
осавь пример без гетеров и сделай одельный пример с кастомным типом

2022-02-09 08:34 UTC, gizeasy commented on src/components/SnackBar/types.ts
> +) => string | number | React.ReactNode | undefined;
только `React.ReactNode  |  undefined`

2022-02-09 08:34 UTC, gizeasy commented on src/components/SnackBar/types.ts
> +    getItemKey?: SnackBarPropGetItemKey<ITEM>;
getItemKey должен быть обязательным если в `ITEM` нет `key: string | number`

2022-02-09 08:34 UTC, gizeasy commented on src/components/SnackBar/types.ts
> +export type SnackBarItemProps<ITEM = Item> = {
пусть принимает на вход уже готовый объект 
```
  key: string | number;
  message?: string | number | React.ReactNode;
  status?: SnackBarItemStatus;
  autoClose?: boolean | number;
  showProgress?: SnackBarItemShowProgressProp;
  icon?: IconComponent;
  actions?: SnackBarPropItemAction[];
  onClose?: (item: Item) => void;
  onAutoClose?: (item: Item) => void;
```

2022-02-09 08:43 UTC, gizeasy requested changes

2022-02-09 08:43 UTC, gizeasy commented on src/components/SnackBar/SnackBar.tsx
>    const refs = useMemo(() => {
Еще тут можешь воспользоваться `useRefs`

2022-02-10 10:28 UTC, N1MBER commented
Fixed

2022-02-11 12:26 UTC, gizeasy requested changes

2022-02-11 12:26 UTC, gizeasy commented on src/components/SnackBar/SnackBar.tsx
> + * @deprecated since version 3.15.1 Item
@deprecated since version 3.16.0 use SnackBarItemDefault

2022-02-11 12:26 UTC, gizeasy commented on src/components/SnackBar/SnackBar.tsx
> +export type SnackBarItemDefault = {
перенеси типы в types

2022-02-11 12:26 UTC, gizeasy commented on src/components/SnackBar/__stories__/SnackBar.stories.tsx
> +        // onAutoClose: () => dispatchItems({ type: 'remove', key }),
удали коменарий

2022-02-11 12:26 UTC, gizeasy commented on src/components/SnackBar/__stories__/SnackBar.stories.tsx
> +      key: key.toString(),
`key.toString` совсем ведь не обязательно

2022-02-11 12:26 UTC, gizeasy commented on src/components/SnackBar/__stories__/examples/SnackBarExampleButtons/SnackBarExampleButtons.tsx
> +        getItemActions={(item) => getActions(item.buttons)}
удобнее в 1000 раз стало!))

2022-02-11 12:26 UTC, gizeasy commented on src/components/SnackBar/__stories__/examples/SnackBarExampleButtons/SnackBarExampleButtons.tsx
> +        getItemActions={(item) => getActions(item.buttons)}
только лучше будет если `getActions` будет на вход получать `item` а не `buttons`
тогда в компоненте оно будет выглядеть чище да и не буде пересоздаваться функция при каждом рендере

`getItemActions={(item) => getActions(item.buttons)}` -> `getItemActions={getActions}`

2022-02-11 12:26 UTC, gizeasy commented on src/components/SnackBar/__stories__/examples/SnackBarExampleIcon/SnackBarExampleIcon.tsx
> +        getItemIcon={(item) => getIcon(item.status)}
будет лучше если getIcon будет на вход получать item а не status

2022-02-11 12:26 UTC, gizeasy commented on src/components/SnackBar/__stories__/examples/SnackBarExampleStatus/SnackBarExampleStatus.tsx
> +        getItemStatus={(item) => getStatus(item.criticality)}
будет лучше если getStatus будет на вход получать item а не criticality

2022-02-11 12:26 UTC, gizeasy commented on src/components/SnackBar/helper.ts
> +  } as SnackBarProps<ITEM> & Required<Mappers<ITEM>>;
`as SnackBarProps<ITEM> & Required<Mappers<ITEM>>;`

приведение совсем не обязательно

посмотри как сделано [тут](https://github.com/consta-design-system/header/blob/dev/src/Menu/helpers.ts)

2022-02-11 13:07 UTC, gizeasy requested changes

2022-02-11 13:07 UTC, gizeasy commented on src/components/SnackBar/types.ts
> +export type SnackBarProps<ITEM = SnackBarItemDefault> = PropsWithHTMLAttributes<
нет условия на наличие key в item чтобы сделать `getItemKey` обязательным

2022-02-15 13:46 UTC, gizeasy requested changes

2022-02-15 13:46 UTC, gizeasy commented on src/components/SnackBar/types.ts
> +export type SnackBarPropGetItemKey<ITEM> = (item: ITEM) => string;
разреши ключ `string | number` раньше ведь так и было

2022-02-15 13:46 UTC, gizeasy commented on src/components/SnackBar/SnackBar.tsx
> +const getItem: GetItem = (item, params) => {
Почему бы не вынести в хелперы?

2022-02-18 07:25 UTC, merged