Feat/context menu canary
consta-design-system/uikit pull request #2079
Opened 2022-02-22 19:15 UTC by N1MBER

closes #1929

Добавлен компонент ContextMenuCanary с документацией и примерами.
Переработан компонент, типы, а также исправлены недочеты

2022-02-24 10:21 UTC, gizeasy requested changes

2022-02-24 10:21 UTC, gizeasy commented on src/components/ContextMenuCanary/ContextMenuLevel/ContextMenuLevel.tsx
> +            {group.group && renderHeader(getGroupLabel(group.group), groupIndex === 0, size)}
на самом деле на группы разбивается когда и нет групп но указан groupId в элементе.
Рендери header без условия, таким образом мы дадим делить на группы без указания групп, это надо когда нужно просто визуальное разделение без подписей

2022-02-24 10:21 UTC, gizeasy commented on src/components/ContextMenuCanary/ContextMenuLevelGroup/ContextMenuLevelGroup.tsx
> +function ContextMenuLevelGroupRender(
ContextMenuLevels может по мне так тут нет логической группировки просто вынесли уровни в отдельный компонент?

2022-02-24 10:21 UTC, gizeasy commented on src/components/ContextMenuCanary/ContextMenuLevelGroup/ContextMenuLevelGroup.tsx
> +import '../ContextMenu.css';
перенеси стили в этот компонент

2022-02-27 12:49 UTC, N1MBER commented on src/components/ContextMenuCanary/ContextMenuCanary.tsx
> +  useEffect(() => {
@gizeasy isOpen нужен для того чтобы использовать useDebounce для проигрывания анимации закрытия

2022-03-01 13:12 UTC, gizeasy requested changes

2022-03-01 13:12 UTC, gizeasy commented on src/components/ContextMenuCanary/helper.ts
> +export const getMappersAndProps = <ITEM, GROUP>(
Я вот думаю а нужна ли вот эта деструкторизация?
почему прямо в компоненте не сделать просто 
const {getItemKey, ... , ...otherProps} = props?

а в getItem можно закинуть просто все пропсы getItem(item, props)

2022-03-01 13:12 UTC, gizeasy commented on src/components/ContextMenuCanary/ContextMenuLevel/ContextMenuLevel.tsx
> +              const standardizedItem = getItem(item, itemMappers);
Не нравится что часть данных возвращается из `getItem` а часть расчитывается тут, так может все будем возращать из getItem или все сюда перенесем?

2022-03-01 13:12 UTC, gizeasy commented on src/components/ContextMenuCanary/ContextMenuLevel/ContextMenuLevel.tsx
> +              const atributes = { ...standardizedItem }.attributes ?? {};
Без этого ни как?

2022-03-09 05:55 UTC, arhayka requested changes
Ставлю статус Request changes, чтобы было понятно, что надо доку поправить. Но я сама  поправлю.

2022-03-09 05:55 UTC, arhayka commented on src/components/ContextMenuCanary/__stories__/ContextMenu.docs.mdx
> +| Свойство                                                           | Тип                                                                                                                 | По умолчан
тут осталась старая табличка, так выкладывать нельзя. я попробую успеть поправить сегодня

2022-03-09 08:14 UTC, arhayka approved these changes

2022-03-10 08:45 UTC, gizeasy requested changes

2022-03-10 08:45 UTC, gizeasy commented on src/components/ContextMenuCanary/ContextMenuLevel/ContextMenuLevel.tsx
> +    size = contextMenuDefaultSize,
очень сного просов и огни были сгрупированны, верни пожалуйста групировку

2022-03-10 08:45 UTC, gizeasy commented on src/components/ContextMenuCanary/ContextMenuLevel/ContextMenuLevel.tsx
> +  useEffect(() => {
совсем нет обходимости, всю анимацию можно было сделать сверху, как в библиотеке хеадер

2022-03-10 08:45 UTC, gizeasy commented on src/components/ContextMenuCanary/ContextMenuLevel/ContextMenuLevel.tsx
> +  useEffect(() => {
совсем нет обходимости, всю анимацию можно было сделать сверху, как в библиотеке хеадер

2022-03-10 08:45 UTC, gizeasy commented on src/components/ContextMenuCanary/ContextMenuLevel/ContextMenuLevel.tsx
> +  const onMouseEnter = (item: ITEM, itemIndex: string) => {
Относится к item, перенеси пожалуйста getItem

2022-03-10 08:45 UTC, gizeasy commented on src/components/ContextMenuCanary/ContextMenuLevel/ContextMenuLevel.tsx
> +  const onMouseEnter = (item: ITEM, itemIndex: string) => {
Относится к item, перенеси пожалуйста getItem

2022-03-10 08:45 UTC, gizeasy commented on src/components/ContextMenuCanary/ContextMenuLevel/ContextMenuLevel.tsx
> +                  ref={itemsRefs[itemIndex]}
Много пропсов еще существуют вне getItem, посему бы их туда не поместить? 
Ну или вообще отказаться от getItem? 
Сейчас просто не понимаю этого логического разделения вроде все пропсы для Item указываеем, а ты их зачем то поделил на те которые из функции и те которые на прямую кидаются.

2022-03-10 08:45 UTC, gizeasy commented on src/components/ContextMenuCanary/ContextMenuLevel/ContextMenuLevel.tsx
> +                  ref={itemsRefs[itemIndex]}
Много пропсов еще существуют вне getItem, посему бы их туда не поместить? 
Ну или вообще отказаться от getItem? 
Сейчас просто не понимаю этого логического разделения вроде все пропсы для Item указываеем, а ты их зачем то поделил на те которые из функции и те которые на прямую кидаются.

2022-03-15 14:43 UTC, gizeasy requested changes

2022-03-16 14:55 UTC, merged