feat(Popover): rewrite offset type
consta-design-system/uikit pull request #2080
Opened 2022-02-22 20:25 UTC by N1MBER

closes #2061

Добавлена возможность указания `offset` через переменные

2022-02-24 11:05 UTC, gizeasy requested changes

2022-02-24 11:05 UTC, gizeasy commented on src/components/Popover/Popover.tsx
> +          typeof offset === 'string' ? ` + var(--space-${offset})` : ''
`typeof offset === 'string' ? ` + var(--space-${offset})` : ''`
нужно учитывать `direction`

2022-02-24 11:18 UTC, gizeasy requested changes

2022-02-24 11:18 UTC, gizeasy commented on src/components/Popover/Popover.tsx
> +          typeof offset === 'string' ? ` + var(--space-${offset})` : ''
![image](https://user-images.githubusercontent.com/13190808/155512844-1429c11e-5cc5-4637-9e98-11f64cac120f.png)

2022-02-28 10:19 UTC, N1MBER commented on src/components/Popover/Popover.tsx
> +          typeof offset === 'string' ? ` + var(--space-${offset})` : ''
@gizeasy Fixed

2022-03-02 10:42 UTC, gizeasy approved these changes

2022-03-02 10:43 UTC, merged