feat(BreadcrumbsCanary): add inner submenu
consta-design-system/uikit pull request #2183
Opened 2022-04-04 12:10 UTC by N1MBER

closes #2075

Добавил контекстное меню для вложенных пунктов навигации

2022-04-06 09:29 UTC, gizeasy commented on src/components/BreadcrumbsCanary/BreadcrumbsItem/BreadcrumbsItem.tsx
> +          anchorRef={breadcrumbsItemRef}
Договаривались же сделать якорем саму галочку

2022-04-06 10:12 UTC, arhayka approved these changes

2022-04-06 12:33 UTC, gizeasy requested changes

2022-04-06 12:33 UTC, gizeasy commented on src/components/BreadcrumbsCanary/BreadcrumbsItem/BreadcrumbsItem.css
> +    &_hovered {
![image](https://user-images.githubusercontent.com/13190808/161975174-f6cd4fb1-4726-4247-949b-6ab76481ddbf.png)
надо разделить ховер ефект на текст и на кнопку

2022-04-13 09:36 UTC, gizeasy approved these changes

2022-04-13 09:37 UTC, merged