docs(common): add SVG parameters to create icon docs
consta-design-system/uikit pull request #2237
Opened 2022-04-20 09:40 UTC by arhayka

closes #2207

## Описание изменений

Написала, как подготовить SVG для иконки

2022-04-20 11:24 UTC, kolebayev approved these changes

2022-04-22 10:01 UTC, gizeasy requested changes

2022-04-22 10:01 UTC, gizeasy commented on docs/common/developers/createIcons.stories.mdx
> +<svg width="16" height="16" viewBox="0 0 16 16" className="Icon-Svg" xmlns="http://www.w3.org/2000/svg">
на самом деле нет необходимости, на выходе компонент буде принимать доступные свойства для `svg `в том числе и `className`, а createIcon уже сам накинет необходимый класс

2022-04-26 13:12 UTC, gizeasy approved these changes

2022-04-26 13:12 UTC, merged