docs(Snackbar): add adaptive section
consta-design-system/uikit pull request #2261
Opened 2022-04-27 13:03 UTC by arhayka

## Описание изменений

Добавила раздел про адаптивность, скопировала абзац из фигмы. И небольшой пример сделала снекбара в карточке.

2022-04-27 14:54 UTC, gizeasy requested changes

2022-04-27 14:54 UTC, gizeasy commented on src/components/SnackBar/__stories__/SnackBar.docs.mdx
> +Максимальная ширина `SnackBar` всегда равна 400 px. Чтобы текст хорошо выглядел
```css
width: 100%;
max-width: calc(400px + var(--space-xs) * 2);
```

то есть он сам уже под контейнер, если контейнер 300 то снекбар буддет 300

2022-05-04 12:07 UTC, arhayka commented on src/components/SnackBar/__stories__/SnackBar.docs.mdx
> +Максимальная ширина `SnackBar` всегда равна 400 px. Чтобы текст хорошо выглядел
хм, а в фигме у нас написано про 400 пикселей. где правда?

2022-05-04 13:24 UTC, gizeasy approved these changes

2022-05-04 13:24 UTC, merged