feat(ListCanary): add new component
consta-design-system/uikit pull request #2809
Opened 2022-12-07 08:15 UTC by N1MBER

2022-12-29 08:08 UTC, gizeasy requested changes

2022-12-29 08:08 UTC, gizeasy commented on src/components/ListCanary/ListItem/ListItem.tsx
> +        role="option"
Не всегда listItem будет иметь `role="option"` лучше задавать с верху в конкреных случаях

2022-12-29 08:08 UTC, gizeasy commented on src/components/ListCanary/ListItem/ListItem.tsx
> +            {rightSide}
для `rightSide` и  `leftSide` нужно сделать так что можно передать массив данных и они отрисуюся сразу с нужными осупами, в контекст меню посмори

2022-12-29 08:08 UTC, gizeasy commented on src/components/ListCanary/ListCanary.tsx
> +    items,
`useSelect` не надо зааскивать в список, эти компоненты должны овечать только за внешний вид

2022-12-29 09:22 UTC, gizeasy requested changes

2022-12-29 09:22 UTC, gizeasy commented on src/components/ListCanary/ListItem/ListItem.tsx
> +        role="option"
tabIndex={0}

2022-12-29 09:22 UTC, gizeasy commented on src/components/ListCanary/ListItem/ListItem.tsx
> +        role="option"
aria-selected

2022-12-29 09:22 UTC, gizeasy commented on src/components/ListCanary/ListItem/ListItem.tsx
> +        role="option"
onKeyDown пусть разворачивается из {...otherProps}

2022-12-29 09:22 UTC, gizeasy commented on src/components/ListCanary/ListCanary.tsx
> +  containerRef.current?.focus();
??

2022-12-29 09:22 UTC, gizeasy commented on src/components/ListCanary/ListCanary.tsx
> +        if (isOptionForCreate(group)) {
isOptionForCreate скорее всего не надо

2023-01-11 10:38 UTC, gizeasy requested changes

2023-01-11 10:38 UTC, gizeasy commented on src/components/ListCanary/MixList/MixList.tsx
> +export const cnMixList: CnList = (props, classNames = []) => {
Зачем? MixList?

2023-01-11 10:38 UTC, gizeasy commented on src/components/ListCanary/ListLoader/ListLoader.css
> +          var(--control-space-m) / 2 + var(--control-text-size-xs)
--control-text-size-xs - задается с верху и нужно описать что задается с верху

2023-01-11 10:38 UTC, gizeasy commented on src/components/ListCanary/MixList/MixList.tsx
> +export const cnMixList: CnList = (props, classNames = []) => {
Если хочешь оставить микс для обертки дропдаунов, думаю стоит его назвать как `ListDropdown` или `ListBox` второе кажется лучше

Ну или брать MixCard поправить в нем `form` и добавить возможнось указания цвета бародера либо с верху либо через статуc

2023-01-11 10:38 UTC, gizeasy commented on src/components/ListCanary/MixList/MixList.tsx
> +export const cnMixList: CnList = (props, classNames = []) => {
из приморов убрать эту обертку, оставить только там где отдельно про обертку говорить будешь

2023-01-11 10:38 UTC, gizeasy commented on src/components/ListCanary/__stand__/List.dev.stand.mdx
> +import { ListExampleItems } from './examples/ListExampleItems/ListExampleItems';
В документацию добавить доку по каждому внутреннему компоненту с примерами и табличкой API

2023-01-11 10:38 UTC, gizeasy commented on src/components/ListCanary/__stand__/List.dev.stand.mdx
> +import { ListExampleItems } from './examples/ListExampleItems/ListExampleItems';
Ну и кратким описанием зачем этот компонент

2023-01-11 10:38 UTC, gizeasy commented on src/components/ListCanary/MixList/MixList.tsx
> +export const cnMixList: CnList = (props, classNames = []) => {
classNames = [] , думаю можно не указывать значение по умолчанию

2023-01-11 10:38 UTC, gizeasy commented on src/components/ListCanary/MixList/MixList.css
> +.MixList {
Не думал брать компонент MixCard, кажется по визуальным силям все тоже самое,`form` надо будет только подправить

2023-01-11 10:38 UTC, gizeasy commented on src/components/ListCanary/index.tsx
> +export * from './helper';
Давай не будем отдавать хелперы наружу

2023-01-12 12:42 UTC, gizeasy requested changes

2023-01-12 12:42 UTC, gizeasy commented on src/components/ListCanary/__stand__/List.stand.tsx
> +  description: 'Список. Компонент для выбора и отображения элементов списка.',
` для выбора` - уже нет

2023-01-12 12:42 UTC, gizeasy commented on src/components/ListCanary/__stand__/List.stand.mdx
> +Список. Позволяет выбрать один или несколько вариантов.
уже просто вывод, и стоит написать что можно использовать отдельные его части

2023-01-12 12:42 UTC, gizeasy commented on src/components/ListCanary/ListItem/ListItem.css
> +  &:hover {
давай ховер эыект и курсор поинтер завяжем на условие
если есть onClick и не задизейблен

2023-01-12 12:42 UTC, gizeasy commented on src/components/ListCanary/ListItem/ListItem.tsx
> +  const handleClick: React.MouseEventHandler<HTMLDivElement> = (e) => {
```ts
const handleClick: React.MouseEventHandler<HTMLDivElement> | undefined =
    onClick && !disabled ? onClick : undefined;
```

далее можем завязать стили на `handleClick` (в css оставил комент зачем)
и также мы не создаем новую функцию на каждый рендер а просто проксируем далее или не проксируем

2023-01-12 14:18 UTC, BagenovA requested changes

2023-01-12 14:18 UTC, BagenovA commented on src/components/ListCanary/__stand__/List.dev.stand.mdx
> +Чтобы разбить элементы списка на группы, передайте массив групп в свойство `groups`. Тип свойства `groups` по умолчанию равен [DefaultListGroup](#свойства). Что внутри:
Вариант

2023-01-12 19:10 UTC, BagenovA requested changes

2023-01-12 19:10 UTC, BagenovA commented on src/components/ListCanary/__stand__/List.dev.stand.mdx
> +- [Загрузчик](#Загрузчик)
Гиперссылка не активна

2023-01-12 23:48 UTC, BagenovA requested changes

2023-01-12 23:48 UTC, BagenovA commented on src/components/ListCanary/__stand__/List.dev.stand.mdx
> +| `getItemActive?`                                        | `ListPropGetItemActive<ITEM>`                          | `(item) => item.active`      | Функция для определения активен ли элемент
Возможно лучше: Функция для определения активности элемента

2023-01-12 23:48 UTC, BagenovA commented on src/components/ListCanary/__stand__/List.dev.stand.mdx
> +| `getItemRightAs?`                                       | `ListPropGetItemAs<ITEM>`                              | `(item) => item.as`          | Функция для определения HTML-тега для рендера элеме
Функция определения HTML-тега для рендера элемента

2023-01-12 23:48 UTC, BagenovA commented on src/components/ListCanary/__stand__/List.dev.stand.mdx
> +| `isLoading?`                                            | `boolean`                                              | -                            | При `true` будет отображаться лоудер загрузки
При true будет отображаться loader загрузки

2023-01-12 23:48 UTC, BagenovA commented on src/components/ListCanary/__stand__/List.dev.stand.mdx
> +| `ariaLabel?`                                            | `string`                                               | -                            | `aria` атрибут для поля ввода
Возможно лучше: Атрибут aria для поля ввода

2023-01-12 23:48 UTC, BagenovA commented on src/components/ListCanary/__stand__/List.stand.mdx
> +Список. Может отображать пункты выбора или список меню.
Возможно лучше: Отображение пунктов выбора или списка меню.

2023-01-12 23:48 UTC, BagenovA commented on src/components/ListCanary/__stand__/List.dev.stand.mdx
> +- `as` - HTML-тэг компонента
Изменить на:

HTML-тег компонента

2023-01-13 07:36 UTC, Lyubavskaya commented on src/components/ListCanary/__stand__/List.dev.stand.mdx
> +- [Содержимое](#содержимое-списка)
Не-не, тут именно описание содержимого, это не содержание. См., например, Modal. 
Заголовка "Содержание" мы нигде не ставим в документации.

2023-01-13 07:42 UTC, Lyubavskaya commented
Нет отступа:
![image](https://user-images.githubusercontent.com/75978078/212265103-8ce4a1fb-8230-4302-9c5a-a2e4f50d1336.png)

2023-01-13 07:43 UTC, Lyubavskaya commented
Нужно добавить песочницу

2023-01-13 08:33 UTC, N1MBER commented on src/components/ListCanary/__stand__/List.dev.stand.mdx
> +  - [Варианты](#варианты)
На сколько вижу иерархия выстроена правильно, если нет поправь пожалуйста сама или хотя бы укажи конкретное место

2023-01-13 08:40 UTC, BagenovA requested changes

2023-01-13 08:40 UTC, BagenovA commented on src/components/ListCanary/__stand__/List.dev.stand.mdx
> +- [Содержимое](#содержимое-списка)
Согласно, что термин "Содержание" неудачный в этом контексте. Какая была логика: Содержимое относится к телу страницы (ко всему контенту, который идёт с кодом, описанием свойств и проч), Содержание - заголовок списка меню. Разнести заголовки этих блоков было бы правильно по редполитике. Можно попробовать заголовок списка "На этой странице".

2023-01-13 08:47 UTC, N1MBER commented on src/components/ListCanary/__stand__/List.dev.stand.mdx
> +Данный компонент представляет из себя элемент-кнопку при помощи которой можно добавить новый элемент списка.
там просто пример, что мол придумывайте себе обработчик который будет добавлять новый элемент

2023-01-13 09:05 UTC, BagenovA commented on src/components/ListCanary/__stand__/List.dev.stand.mdx
> +  - [Варианты](#варианты)
На мой взгляд меню списка должно выглядеть как на скрине [https://disk.yandex.ru/i/_NbXchJ4O5RD6w](url)

2023-01-13 09:19 UTC, BagenovA commented on src/components/ListCanary/__stand__/List.dev.stand.mdx
> +  - [Варианты](#варианты)
Что я имела ввиду: по содержанию блоков, пункты Выбранное значение, Неактивный вариант и Группы вариантов как будто бы должны объединяться в группу под заголовком "Варианты". Сейчас они сгруппированы под заголовком "Содержимое" (посмотри как это выглядит на странице портала). Я думаю, что "Содержимое" относится ко всему списку меню.

2023-01-13 09:23 UTC, BagenovA commented on src/components/ListCanary/__stand__/List.dev.stand.mdx
> +Данный компонент представляет из себя элемент-кнопку при помощи которой можно добавить новый элемент списка.
Стало быть моя логика верна. Оставляем предложенный мной вариант описания?

2023-01-13 09:47 UTC, BagenovA requested changes

2023-01-13 09:47 UTC, BagenovA commented on src/components/ListCanary/__stand__/List.dev.stand.mdx
> +Элементы выпадающего списка можно описать в массиве `items`. Тип свойства `items` по умолчанию равен [DefaultListItem](#свойства). Что внутри:
Заменить "Что внутри" на "Значения"

2023-01-13 09:47 UTC, BagenovA commented on src/components/ListCanary/__stand__/List.dev.stand.mdx
> +<ListExampleItems />
Что имела ввиду (здесь и в других таких же комментах): посмотреть как отображается/выглядит пример на странице портала. Если есть баги (нет отступов, пример не демонстрирует описанное свойство, цвета не те, выравнивание скачет и проч), то надо поправить.

2023-01-13 09:47 UTC, BagenovA commented on src/components/ListCanary/__stand__/List.dev.stand.mdx
> +Чтобы разбить элементы списка на группы, передайте массив групп в свойство `groups`. Тип свойства `groups` по умолчанию равен [DefaultListGroup](#свойства). Что внутри:
Заменить "Что внутри" на "Значения"

2023-01-13 09:47 UTC, BagenovA commented on src/components/ListCanary/__stand__/List.dev.stand.mdx
> +| `as?`        | `keyof JSX.IntrinsicElements` | -            | HTML-тэг компонента             |
Вместо "тэг" везде пишем "тег"

2023-01-16 08:42 UTC, gizeasy requested changes

2023-01-16 08:42 UTC, gizeasy commented on src/components/ListCanary/ListItem/ListItem.css
> +      --list-item-vertical-space: calc(var(--control-space-s) / 4);
var(--control-space-s) убери переменные `control` со всех компонентов

2023-01-16 10:53 UTC, BagenovA requested changes

2023-01-16 10:53 UTC, BagenovA commented on src/components/ListCanary/__stand__/List.dev.stand.mdx
> +        Все результаты
Между Все результаты и Первая группа должен быть пробел или отступ?

2023-01-16 13:04 UTC, gizeasy approved these changes

2023-01-16 13:22 UTC, merged