docs(TextField): add examples with imask usage
consta-design-system/uikit pull request #2890
Opened 2023-02-07 08:46 UTC by N1MBER

closes #1083

2023-02-07 12:50 UTC, N1MBER commented
Сделать хук useImask который принимает либо объект либо стрингу, + проверить в примерах динамическую смену значения

2023-02-10 12:18 UTC, gizeasy requested changes

2023-02-10 12:18 UTC, gizeasy commented on src/components/TextField/useIMask.ts
> +
давай так:
```ts
type Props<MASK extends IMask.AnyMaskedOptions> = {
  value: string | null;
  maskOptions: string | MASK;
  onChange?: (value: string | null, params: { e: Event; value:  string | null; }) => void;
};
```

таким образом мы сможем вызывать хук не создавая лишнюю функцию

```ts
const [value, setValue] = useState<string | null>(null);
const { inputRef } = useIMask({
    value,
    onChange: setValue,
    maskOptions: '+{7}(000)000-00-00',
});
```

2023-02-13 13:56 UTC, gizeasy commented
pipe, и value обязательный

2023-02-14 15:53 UTC, gizeasy requested changes

2023-02-14 15:53 UTC, gizeasy commented on src/components/TextField/__stand__/TextField.dev.stand.mdx
> +      <Button
<img width="460" alt="image" src="https://user-images.githubusercontent.com/13190808/218788626-f66cbf24-be1b-4ed6-8f5f-2862d0e04605.png">

оберни в див чтоб не смотрелось что все съехало

2023-02-14 16:30 UTC, merged

2023-03-01 18:01 UTC, BagenovA commented on src/components/TextField/__stand__/TextField.dev.stand.mdx
> +- [Маскированние](#маскирование)
Исправить на "Маскирование"

2023-03-01 18:03 UTC, BagenovA commented on src/components/TextField/__stand__/TextField.dev.stand.mdx
> +  - [Изменения из вне](#изменения-из-вне)
Извне пишется слитно

2023-03-01 18:05 UTC, BagenovA commented on src/components/TextField/__stand__/TextField.dev.stand.mdx
> +В случае когда значение `TextField` может меняться из вне (изменения происходят не из поля ввода), необходимо использовать функцию [`IMask.pipe`](https://imask.js.org/guide.html#pipe),
Лучше так: Когда значение TextField меняется извне (не из поля ввода), необходимо использовать функцию [IMask.pipe], для преобразования значения под формат маски.

2023-03-01 18:11 UTC, BagenovA commented
В Содержимое не работает ссылка "Шаг, набор значений и диапазон"