feat(Tabs): add new getters
consta-design-system/uikit pull request #2911
Opened 2023-02-16 14:50 UTC by gizeasy

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2023-02-16 15:37 UTC, BagenovA requested changes

2023-02-16 15:37 UTC, BagenovA commented on src/components/Tabs/__stand__/Tabs.dev.stand.mdx
> +По умолчантю используется следующий тип, но компонент может принимать произвольный тип.
Может так: По умолчанию используется тип 'TabsItemDefault'. Однако компонент может принимать и произвольный тип.

2023-02-16 15:37 UTC, BagenovA commented on src/components/Tabs/__stand__/Tabs.dev.stand.mdx
> +`label`, `leftIcon`, `rightIcon`, `rightSide`, `leftSide`, `disabled` для элемента компонент будет опимисично брать операясь на тип по умолчанию.
Наверно так: Свойства label, leftIcon, rightIcon, rightSide, leftSide, disabled компонент будет оптимистично брать опираясь на тип по умолчанию. Можно указать компоненту другое место хранения свойств таба.

2023-02-16 15:37 UTC, BagenovA commented on src/components/Tabs/__stand__/Tabs.dev.stand.mdx
> +<TabsExampleIcon />
В примере, где только иконки - по наведению должен появляться текст или нет?

2023-02-16 15:37 UTC, BagenovA commented on src/components/Tabs/__stand__/Tabs.dev.stand.mdx
> +Если передать массив элементов то отступы между элементами дополнительно контента расставятся автоматически.
Исправить на: Если передать массив элементов, то отступы, между элементами дополнительного контента, расставятся автоматически.

2023-02-16 15:37 UTC, BagenovA commented on src/components/Tabs/__stand__/Tabs.dev.stand.mdx
> +## Не акивные элементы
Исправить на: Неактивные элементы

2023-02-16 15:37 UTC, BagenovA commented on src/components/Tabs/__stand__/Tabs.dev.stand.mdx
> +Вы можете отключить как все табы используя свойство `disabled`
Исправить на: Вы можете отключить как все табы, используя свойство disabled, так и отдельный элемент, указав disabled у элемента или используя getItemDisabled.

2023-02-16 15:37 UTC, BagenovA commented on src/components/Tabs/__stand__/Tabs.dev.stand.mdx
>  Есть три размера — `xs`, `s` и `m` (основной, включен по умолчанию).
Может лучше так: Есть три размера — xs, s и m. Основной размер m, включен по умолчанию.

2023-02-16 15:37 UTC, BagenovA commented on src/components/Tabs/__stand__/Tabs.dev.stand.mdx
>  - [Адаптивность](#адаптивность)
Добавить в раздел Адаптивность подразделы Выпадающий список и Прокрутка

2023-02-16 15:37 UTC, BagenovA commented on src/components/Tabs/__stand__/Tabs.dev.stand.mdx
> -- [Кастомизация](#кастомизация)
На странице контент по Кастомизации есть, а из Содержимого пункт убрали.

2023-02-17 10:46 UTC, gizeasy commented on src/components/Tabs/__stand__/Tabs.dev.stand.mdx
>  - [Адаптивность](#адаптивность)
Уберу из контента тоже, так как сейчас эти примеры можно реализовать с помошью другого апи, а эту функциональность в процессе выпилим из компонента

2023-02-17 10:46 UTC, gizeasy commented on src/components/Tabs/__stand__/Tabs.dev.stand.mdx
> -- [Кастомизация](#кастомизация)
Уберу из контента тоже, так как сейчас эти примеры можно реализовать с помошью другого апи, а эту функциональность в процессе выпилим из компонента

2023-02-22 11:28 UTC, merged