feat(FieldLabel): added prop icon
consta-design-system/uikit pull request #2949
Opened 2023-03-13 10:44 UTC by N1MBER

closes #2948

2023-03-15 10:58 UTC, BagenovA requested changes

2023-03-15 10:58 UTC, BagenovA commented on src/components/TextField/__stand__/TextField.dev.stand.mdx
> +Также к лейблу можно xдобавить иконку используя свойство `labelIcon`.
Исправить опечатку в слове "добавить"

2023-03-15 10:58 UTC, BagenovA commented on src/components/TextField/__stand__/TextField.dev.stand.mdx
>  | [`withClearButton?`](#кнопка-для-очистки-поля)        | `boolean`
Может лучше так: Отображение кнопки-крестик для очистки поля ввода

2023-03-15 10:58 UTC, BagenovA commented on src/components/UserSelect/__stand__/UserSelect.dev.stand.mdx
> +Также к лейблу можно xдобавить иконку используя свойство `labelIcon`.
Исправить опечатку в слове "добавить"

2023-03-15 10:58 UTC, BagenovA commented on src/components/UserSelect/__stand__/UserSelect.dev.stand.mdx
>  | [`placeholder?`](#подсказка)                                        | `string`                                               | -                                                             | Подска
Исправить на: Подсказка отображается, когда вариант не выбран

2023-03-15 15:15 UTC, gizeasy approved these changes

2023-03-23 10:48 UTC, gizeasy requested changes

2023-03-24 09:00 UTC, linturaven commented on src/components/FieldLabel/FieldLabel.css
> +        margin-right: calc(var(--space-2xs) + var(--space-3xs));
Я обычно юзаю всё кратное 4 и иногда 2px, проблем не вызывает

2023-03-24 09:07 UTC, gizeasy commented on src/components/FieldLabel/FieldLabel.css
> +        margin-right: calc(var(--space-2xs) + var(--space-3xs));
@N1MBER 
```css
--space-3xs: 2px;
--space-2xs: 4px;
--space-xs: 8px;
--space-s: 12px;
```
calc(var(--space-2xs) + var(--space-3xs)); равнозначно var(--space-3xs)

2023-03-24 10:32 UTC, gizeasy commented on src/components/FieldLabel/FieldLabel.css
> +        margin-right: calc(var(--space-2xs) + var(--space-3xs));
@hell0anna про отступ от иконки при размере `m`

2023-03-24 11:41 UTC, hell0anna commented on src/components/FieldLabel/FieldLabel.css
> +        margin-right: calc(var(--space-2xs) + var(--space-3xs));
давайте сделаем 4рх тут и во всех селектах (select, combobox, userSelect, autoComplete)

2023-03-27 11:25 UTC, gizeasy approved these changes

2023-03-27 11:26 UTC, merged