fix(Discrepancies): fix style mistakes
consta-design-system/uikit pull request #3014
Opened 2023-04-24 09:20 UTC by N1MBER

closes #2941, #2972

2023-04-27 11:00 UTC, gizeasy requested changes

2023-05-22 10:32 UTC, gizeasy approved these changes

2023-05-22 14:27 UTC, N1MBER commented on src/components/Card/Card.css
> +.Card {
Это одно из основных расхождений по карточке, надо будет с Лешей и Аней обсудить

2023-06-20 12:56 UTC, hell0anna reviewed
давайте обсудим, что делать с этим ломающим изменением)

2023-07-12 12:50 UTC, merged