fix(Steps): fix discrepancies between design and code
consta-design-system/uikit pull request #3055
Opened 2023-05-22 08:54 UTC by N1MBER

#3001

2023-05-22 10:59 UTC, gizeasy requested changes

2023-05-22 10:59 UTC, gizeasy commented on src/components/Steps/Steps.tsx
> -              getItemCompleted?.(item)
А зачем? ведь на проекте можно написать getItemLabel таким образом чтобы такой формат указывать, просто в getItemLabel добавь еще и индекс на всякий случай. Кажется что такое поведение по умолчанию не всем нужно, а еще это ломающее изменение

2023-05-26 10:33 UTC, gizeasy approved these changes

2023-05-29 06:55 UTC, hell0anna commented
не хватает размера S, был добавлен в дизайне

2023-05-29 13:54 UTC, hell0anna requested changes
не хватает размера S, был добавлен в дизайне

2023-05-30 10:36 UTC, BagenovA requested changes

2023-05-30 10:36 UTC, BagenovA commented on src/components/Steps/__stand__/Steps.dev.stand.mdx
>  | [`getItemCompleted?`](#пройденные-шаги) | `StepsPropGetSkipped`   | -            | Получает флаг завершен ли шаг                                                        |
Может так: Получает флаг, если шаг завершен

2023-05-30 10:36 UTC, BagenovA commented on src/components/Steps/__stand__/Steps.dev.stand.mdx
>  | [`getItemSkipped?`](#пропущенные-шаги)  | `StepsPropGetCompleted` | -            | Получает флаг пропущен ли шаг                                                        |
Вариант: Получает флаг, если шаг пропущен

2023-05-30 10:36 UTC, BagenovA commented on src/components/Steps/__tests__/Steps.test.tsx
>        it('лэйбл совпадает', () => {
Изменить "лэйбл" на "лейбл"

2023-07-12 13:15 UTC, merged