docs(standConfig): add figmaUrl
consta-design-system/uikit pull request #3074
Opened 2023-05-25 11:53 UTC by gizeasy

добавил ссылку на фигму

2023-05-26 09:17 UTC, BagenovA requested changes

2023-05-26 09:22 UTC, gizeasy commented on src/stand/standConfig.ts
> +  figmaUrl: 'https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit',
Возможно, но вомногих других библиотеках просто нет такой страницы и нужно указывать страницу какогонибуть компонента или страницы

2023-05-26 09:25 UTC, gizeasy commented on src/stand/standConfig.ts
> +  figmaUrl: 'https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit',
@linturaven Что думаешь? Мы к чему в итоге придем, будет ли у каждой библиотеки своя фигмовская библиотека? Если нет то думаю делать ссылки просто на странице чтоб одинаково было

2023-05-29 14:04 UTC, hell0anna commented on src/stand/standConfig.ts
> +  figmaUrl: 'https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit',
согласна с Настей, а к каким библиотекам нет фигмовских библиотек и что мы там сейчас показываем?

2023-05-31 10:12 UTC, hell0anna commented on src/stand/standConfig.ts
> +  figmaUrl: 'https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit',
к этой библиотеке есть страница https://www.figma.com/community/file/1045349329378392766
я бы делала там где есть — ссылкой на страницу, если нет — на файл

2023-05-31 10:14 UTC, hell0anna commented on src/stand/standConfig.ts
> +  figmaUrl: 'https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit',
в любом случае, если указываем ссылко на файл — у каждого такого файла есть обложка. Указывать ссылку лучше на нее, как по мне. 
Мб @linturaven другого мнения

2023-06-02 09:04 UTC, merged