feat(Spoiler): add new component
consta-design-system/uikit pull request #3095
Opened 2023-06-01 08:29 UTC by N1MBER

closes #2992

2023-06-02 08:58 UTC, BagenovA requested changes

2023-06-02 08:58 UTC, BagenovA commented on src/components/SpoilerCanary/__stand__/Spoiler.dev.stand.mdx
> +Для переопределения иконок определите свойства `moreIcon` и `lessIcon`, для раскрытия и скрытия содержимого соответственно.
Лучше так: Для переопределения иконок используйте свойства `moreIcon` и `lessIcon`, для раскрытия и скрытия содержимого соответственно.

2023-06-02 08:58 UTC, BagenovA commented on src/components/SpoilerCanary/__stand__/Spoiler.stand.mdx
> +Используется для раскрытия/скрытия содержимого. Экономит пространство, сохраняя визуальный баланс и иерархию информации. Существует 2 вида компонента внешний и встроенный.
В предложении "Существует 2 вида компонента внешний и встроенный." поставить двоеточие.

Существует 2 вида компонента: внешний и встроенный.

2023-06-02 08:58 UTC, BagenovA commented on src/components/SpoilerCanary/__tests__/Spoiler.test.tsx
> +    describe('проверка тэга', () => {
Исправить слово "тэга" на "тега"

2023-06-02 09:18 UTC, gizeasy reviewed
что если сделать переключение иконок как в `Collapse`
Там анимированое изменение стороны и аниморванное изменение иконки.

Думаю можно сделать компонент IconAnimateSwitcher который бы покрывал возможности:
1) Анимация переворота иконки 
2) Анимация смены иконки

2023-06-14 14:23 UTC, gizeasy requested changes

2023-06-14 14:23 UTC, gizeasy commented on src/components/SpoilerCanary/types.ts
> +  type?: 'more' | 'less';
давай `type` переделаем в `boolean` тип, и переименуем в какойнибуть `open`

2023-06-14 14:23 UTC, gizeasy commented on src/components/SpoilerCanary/types.ts
> +  mode?: 'inner' | 'external';
`mode` можно вообще убрать и просто не ставить иконки по умолчанию, если нет иконок то поведение как `inner` если есть то как `external`

2023-06-14 14:23 UTC, gizeasy commented on src/components/SpoilerCanary/types.ts
> +  mode?: 'inner' | 'external';
также если одна иконка то просто при изменение флага `open` меняем угол поворота с 0 на 180
если же есть 2 иконки то меняем одну на другую

2023-06-16 08:17 UTC, gizeasy approved these changes

2023-06-16 08:17 UTC, gizeasy commented on src/components/SpoilerCanary/Spoiler.css
> +  &_underline {
Получается что отдельно это свойство не включить только если иконки нет?

2023-06-19 11:58 UTC, hell0anna commented
кажется не хватает примера с блоком текста, где часть скрывается/раскрывается. Даже в описании написано "Компонент отображает контент в зависимости от флага open", но не показано действие...

2023-06-19 11:59 UTC, hell0anna reviewed
см мой коммент

2023-06-23 09:16 UTC, merged