feat(useVirtualScroll): add hook
consta-design-system/uikit pull request #3108
Opened 2023-06-15 15:25 UTC by gizeasy

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2023-06-16 09:54 UTC, N1MBER commented on src/hooks/useComponentSize/getElementSize.ts
Можно записать так, читаемость не ухудшится да

```tsx
export const getElementSize = (
  el: HTMLElement | SVGGraphicsElement | null,
): ComponentSize => el?.getBoundingClientRect() ?? { width: 0, height: 0 };
```

2023-06-16 09:57 UTC, N1MBER approved these changes

2023-06-16 11:13 UTC, gizeasy commented on src/hooks/useComponentSize/getElementSize.ts
оставлю как есть, все таки все параметры `getBoundingClientRect ` не нужны будут.

2023-06-16 11:13 UTC, gizeasy commented on src/hooks/useComponentSize/getElementSize.ts
оставлю как есть, все таки все параметры getBoundingClientRect  не нужны будут.

2023-06-16 12:26 UTC, BagenovA requested changes

2023-06-16 12:26 UTC, BagenovA commented on src/hooks/useVirtualScrollCanary/__stand__/useVirtualScroll.stand.mdx
> +Хук для огранизации виртуального и бесконечного скролинга.
Слово "скроллинг" с двойной "л"

2023-06-16 12:26 UTC, BagenovA commented on src/hooks/useVirtualScrollCanary/__stand__/useVirtualScroll.stand.mdx
> +# Виртульный скролл
Исправить опечатку в слове "виртуальный"

2023-06-16 12:26 UTC, BagenovA commented on src/hooks/useVirtualScrollCanary/__stand__/useVirtualScroll.stand.mdx
> +| `length`            | `number`                 | -            | Длина массива массива элементов                   |
Убрать дубль слова "массива"

2023-06-16 12:26 UTC, BagenovA commented on src/hooks/useVirtualScrollCanary/__stand__/useVirtualScroll.stand.mdx
> +| `onScrollToBottom?` | `(index:number) => void` | -            | Колбек сработает когда доскролили список до конца |
Может так: Обратный вызов, срабатывающий при прокрутке списка до конца

2023-06-17 10:05 UTC, gizeasy commented on src/hooks/useVirtualScrollCanary/__stand__/useVirtualScroll.stand.mdx
> +| `onScrollToBottom?` | `(index:number) => void` | -            | Колбек сработает когда доскролили список до конца |
![image](https://github.com/consta-design-system/uikit/assets/13190808/13999c7e-77ee-4b3d-b095-e71533d1fb35)

2023-06-17 10:06 UTC, gizeasy commented on src/hooks/useVirtualScrollCanary/__stand__/useVirtualScroll.stand.mdx
> +| `onScrollToBottom?` | `(index:number) => void` | -            | Колбек сработает когда доскролили список до конца |
оставлю колбэк

2023-06-17 10:30 UTC, merged