docs(Table): replace code examples to how to use
consta-design-system/uikit pull request #3124
Opened 2023-06-26 08:02 UTC by N1MBER

closes #2978

2023-06-26 13:29 UTC, BagenovA requested changes

2023-06-27 08:29 UTC, gizeasy requested changes
Еще надо убрать примеры из кнобов

2023-06-27 08:29 UTC, gizeasy commented on src/components/Table/__stand__/Table.use.stand.mdx
> +<TableUseWithBigData />
Пример должен отображать виртуальный скрол, огранич высоту компонента

2023-06-27 08:29 UTC, gizeasy commented on src/components/Table/__stand__/Table.use.stand.mdx
> +<TableUseWithBigData />
Посмотри как должно работать в кнобах

2023-07-18 12:28 UTC, merged