feat(withTooltipCanary): added new hoc
consta-design-system/uikit pull request #3125
Opened 2023-06-26 10:43 UTC by N1MBER

Added hoc for tooltips

closes #3069

2023-06-26 12:58 UTC, BagenovA requested changes

2023-06-26 12:58 UTC, BagenovA commented on src/hocs/withTooltipCanary/__stand__/examples/WithTooltipExampleProps/WithTooltipExampleProps.tsx
> +        <ButtonWithTooltip label="Свойство описано в кнопке" />
Может так: Свойство кнопки описано в подсказке

2023-06-26 12:58 UTC, BagenovA commented on src/hocs/withTooltipCanary/__stand__/examples/WithTooltipExampleText/WithTooltipExampleText.tsx
> +        На мне появится тултип
Лучше так: Здесь появится тултип

2023-06-26 12:58 UTC, BagenovA commented on src/hocs/withTooltipCanary/__stand__/withTooltip.stand.mdx
> +- [Что это](#что-это-такое)
Может лучше так: Что такое тултип

2023-06-26 12:58 UTC, BagenovA commented on src/hocs/withTooltipCanary/__stand__/withTooltip.stand.mdx
> +Напирмер, `withTooltip` можно добавить к обычному тексту (заданному в компоненте `Text`).
Исправить опечатку в слове "например"

2023-06-26 12:58 UTC, BagenovA commented on src/hocs/withTooltipCanary/__stand__/withTooltip.stand.mdx
> +      На мне появится тултип
Лучше так: Здесь появится тултип

2023-06-26 12:58 UTC, BagenovA commented on src/hocs/withTooltipCanary/withTooltip.tsx
> +// функция которая закроет все тултипы на странице кроме текущего с которым взаимодействует пользователь
Лучше так:  функция, которая закроет все тултипы на странице кроме текущего, с которым взаимодействует пользователь

2023-06-26 12:58 UTC, BagenovA commented on src/hocs/withTooltipCanary/withTooltip.tsx
> +    // удаляем только текущую функцию закрытия, нужна если компонент размонтируется
Может так: удаляем только текущую функцию закрытия, которая нужна, если компонент размонтируется

2023-06-26 12:58 UTC, BagenovA commented on src/hocs/withTooltipCanary/withTooltip.tsx
> +    // закрываем все тултипы на странице кроме текущего с которым взаимодействует пользователь
Может так: закрываем все тултипы на странице кроме текущего, с которым взаимодействует пользователь

2023-06-27 08:37 UTC, gizeasy commented on src/hocs/withTooltipCanary/__stand__/examples/WithTooltipExampleMode/WithTooltipExampleMode.tsx
> +import { Button } from '../../../../../components/Button/Button';
давай пути обсолютно указывать серез `##` чтоб так - `##/components/Button`

2023-06-27 08:53 UTC, gizeasy requested changes

2023-06-27 08:53 UTC, gizeasy commented on src/hocs/withTooltipCanary/withTooltip.tsx
> +  Component: COMPONENT_TYPE,
COMPONENT_TYPE extends
      | React.ComponentType<React.PropsWithRef<ComponentProps>>
      | ((props: ComponentProps) => React.ReactElement | null),

Думаю надо ограничить компоненты, 

нужны компонеты которые умеют в 

```
type ComponentProps = {
  onClick?: (() => void) | React.EventHandler<React.MouseEvent>;
  onMouseEnter?: (() => void) | React.MouseEventHandler;
  onMouseLeave?: (() => void) | React.MouseEventHandler;
};
```

2023-06-27 08:53 UTC, gizeasy commented on src/hocs/withTooltipCanary/withTooltip.tsx
> +          {...(otherProps as WithTooltipComponentProps)}
otherProps as WithTooltipComponentProps

думаю надо

{...(componentProps as COMPONENT_PROPS)}

2023-06-27 08:59 UTC, gizeasy commented on src/hocs/withTooltipCanary/withTooltip.tsx
> +          {...(otherProps as WithTooltipComponentProps)}
можно просто {...otherProps}

2023-06-27 08:59 UTC, gizeasy commented on src/hocs/withTooltipCanary/withTooltip.tsx
> +          {...(otherProps as WithTooltipComponentProps)}
коментарий только напиши мол это свойтва компонента

2023-08-16 10:57 UTC, gizeasy commented
Не актуально

2023-08-16 10:57 UTC, closed without merging