Feat/spoiler
consta-design-system/uikit pull request #3132
Opened 2023-06-28 12:45 UTC by N1MBER

closes #2992

2023-06-30 13:01 UTC, BagenovA requested changes

2023-07-10 08:23 UTC, gizeasy requested changes

2023-07-10 08:23 UTC, gizeasy commented on src/components/SpoilerCanary/Spoiler.tsx
> +          ...
Точки и обрезание пусть делают выше компонента

2023-07-10 08:23 UTC, gizeasy commented on src/components/SpoilerCanary/types.ts
> +        mode?: 'dots';
Еще думали что вид пиереключения будет зависить не от модификатора mode, а от заполнености children . Если есть children то preview и fullText не заполняется но заполняется maxHeight.

2023-07-10 08:23 UTC, gizeasy commented on src/components/SpoilerCanary/__stand__/Spoiler.variants.tsx
> +      moreIcon={withIcons ? IconArrowDown : undefined}
Они там и так стрелочи стоят и не заметно на стендах что чтото меняется, давай плюс с минусом воткнешь. А варианта без иконок не будет да? Вроде как хотели у самой кнопки то оставить эту модификачию чтоб можно было ее в свой текст воткнуть

2023-07-10 08:23 UTC, gizeasy commented on src/components/SpoilerCanary/SpoilerButton/SpoilerButton.tsx
> +import { Text } from '../../Text';
абсолютные пути! )) Относительные если только файлики внутри компонента

2023-07-10 08:23 UTC, gizeasy commented on src/components/SpoilerCanary/__stand__/Spoiler.stand.tsx
> +    'https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?type=design&node-id=122771%3A358766&t=exHMZDesj7Vfu8u9-1',
ссылка должна вести на комьюнити

https://www.figma.com/file/xfuh9fLo3qFOICWtnrmQQ1/Consta-UI-Kit-(Community)?type=design&node-id=122771-358250&mode=design&t=cFUvyOJ9qSmNK8bw-0

2023-07-10 08:23 UTC, gizeasy commented on src/components/SpoilerCanary/__stand__/Spoiler.variants.tsx
> +  const params = useMemo(() => {
чтото тут особо и не надо useMemo)) только в память срет))

2023-07-18 10:46 UTC, merged