feat(BadgeGroup): add new component
consta-design-system/uikit pull request #3141
Opened 2023-06-29 21:18 UTC by N1MBER

closes #1941

2023-06-30 12:29 UTC, BagenovA requested changes

2023-06-30 12:29 UTC, BagenovA commented on src/components/BadgeGroup/__stand__/BadgeGroup.dev.stand.mdx
> +- исконка справа — в поле `iconRight` или с помощью функции `getItemIconRight`,
Исправить опечатку в слове "иконка"

2023-07-10 08:31 UTC, gizeasy requested changes

2023-07-10 08:31 UTC, gizeasy commented on src/components/BadgeGroup/BadgeGroup.tsx
> +import './BadgeGroup.css';
https://consta.design/libs/header/components-badges-stable

посмотри пожалуйста тут как организовано скрытие элементов, нужно добавить в твой компонент, вообще задача была про перенос компонента из библиотеки header в uikit

2023-07-12 11:45 UTC, gizeasy requested changes

2023-07-12 11:45 UTC, gizeasy commented on src/components/BadgeGroup/BadgeGroup.tsx
> +    fitMode = 'reduction',
Думаю что по умолчанию нужно переносить и скрывать уже по требованию

2023-07-12 13:06 UTC, gizeasy commented
![image](https://github.com/consta-design-system/uikit/assets/13190808/d73d9926-2d8d-414d-9e29-8e68b26ec91a)

бейдж с цифоркой съехал

2023-07-12 13:09 UTC, gizeasy commented
рефку на more
колбеки на more onClick onBlur onMouseEnter

2023-07-18 09:00 UTC, gizeasy requested changes

2023-07-18 09:00 UTC, gizeasy commented on src/components/BadgeGroup/__stand__/examples/BadgeGroupExampleItems/BadgeGroupExampleItems.tsx
> +        items={[...items]}
почему `items={[...items]}` а не `items={items}`?

И селекторы лучше описывать за компонентом, так правильнее функции не пересоздаются на каждый чих

2023-07-18 10:42 UTC, gizeasy requested changes

2023-07-18 10:42 UTC, gizeasy commented on src/components/BadgeGroup/__stand__/BadgeGroup.dev.stand.mdx
> +export const BadgeGroupExampleItems = () => {
Тут тоже поправь

2023-07-18 12:23 UTC, merged