feat(useResizableContent): added new hook for resize elements
consta-design-system/uikit pull request #3169
Opened 2023-07-12 08:44 UTC by N1MBER

closes #3009

2023-07-14 11:19 UTC, gizeasy requested changes

2023-07-14 11:19 UTC, gizeasy commented on src/hooks/useResizableContent/useResizableContent.ts
> +  useEffect(() => {
Объявление констант вверху события жизненного цикла внизу

2023-07-14 11:19 UTC, gizeasy commented on src/hooks/useResizableContent/__stand__/examples/UseResizableContentLayout/UseResizableContentLayout.tsx
> +  const { sizes: hSizes, handlers: hHandlers } = useResizableContent({
что думаешь если такое апи сделать ?
я вижу плюс в том что сразу моджно назвать переменные и работать уже с нормальными названями, но с другой стороны когда много ячеек ни кто их назвать не будет по отдельности. Скорее этот комент больше мысли в слух))

```tsx
const [[horizontalBlock1,  horizontalBlock2], [deviderHandles]]= useResizableContent({
    refs: [horizontalBlock1Ref, horizontalBlock2Ref],
    direction: 'horizontal',
    container: containerRef,
})
```

2023-07-14 11:19 UTC, gizeasy commented on src/hooks/useResizableContent/useResizableContent.ts
> +  const handlePress = useCallback(
тут конечно ты сделал мемонизацию но ниже по коду ты возвращаешь () => handlePress(index) что есть всегда новая функция

2023-07-14 13:27 UTC, N1MBER commented on src/hooks/useResizableContent/__stand__/examples/UseResizableContentLayout/UseResizableContentLayout.tsx
> +  const { sizes: hSizes, handlers: hHandlers } = useResizableContent({
В целом согласен с твоими мыслями, но тут так как мы и так возвращаем массивы, стоит наверное все же использовать объект

2023-07-17 10:11 UTC, BagenovA requested changes

2023-07-17 10:11 UTC, BagenovA commented on src/hooks/useResizableContent/__stand__/useResizableContent.stand.mdx
> +Хук `useResizableContent` позволяет сделать блоки в контейнере с изменяемыми размерами.
Может так: С помощью хука `useResizableContent` размеры блоков в контейнере можно сделать изменяемыми.

2023-07-18 12:37 UTC, merged