feat(Spoiler): add props clamp, buttonIndent, buttonAlign
consta-design-system/uikit pull request #3197
Opened 2023-08-04 20:52 UTC by gizeasy

closes #3179

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2023-08-07 09:53 UTC, N1MBER commented
clamp лучше переименовать в lineClamp, как название css свойства, так понятнее будет за что отвечает. fullText в content тоже согласен, preview на мой взгляд лучше оставить так как есть

2023-08-07 09:53 UTC, N1MBER approved these changes

2023-08-08 11:24 UTC, BagenovA requested changes

2023-08-08 11:24 UTC, BagenovA commented on src/components/SpoilerCanary/__tests__/Spoiler.test.tsx
> +    it('кнопка не должна отображатся если высота превью схожа с высотой полного текста', () => {
Может так: кнопка не отображается, если высота превью схожа с высотой полного текста

2023-08-08 11:24 UTC, BagenovA commented on src/components/SpoilerCanary/__tests__/Spoiler.test.tsx
> +    it('кнопка должна отображатся если высота превью меньше высоты полного текста', () => {
Может так: кнопка отображается, если высота превью меньше высоты полного текста

2023-08-10 14:03 UTC, gizeasy commented on src/components/SpoilerCanary/__tests__/Spoiler.test.tsx
> +    it('кнопка должна отображатся если высота превью меньше высоты полного текста', () => {
fix

2023-08-10 14:03 UTC, gizeasy commented on src/components/SpoilerCanary/__tests__/Spoiler.test.tsx
> +    it('кнопка не должна отображатся если высота превью схожа с высотой полного текста', () => {
fix

2023-08-10 14:16 UTC, merged