feat(useStyleProps): add useStyleProps
consta-design-system/uikit pull request #3198
Opened 2023-08-05 16:01 UTC by gizeasy

closes #2373

2023-08-07 09:50 UTC, N1MBER approved these changes

2023-08-08 11:18 UTC, BagenovA requested changes

2023-08-08 11:18 UTC, BagenovA commented on src/hooks/useStyleProps/__stand__/useStyleProps.stand.mdx
> +Этот хук позволяет получить значение CSS свойств. Хук имеет подписку на изменение темы, и всегда возвразает актуальные свойства.
Может так: Хук позволяет получить значение CSS свойств. Имеет подписку на изменение темы и всегда возвращает актуальные свойства.

2023-08-08 11:18 UTC, BagenovA commented on src/hooks/useStyleProps/__stand__/useStyleProps.stand.mdx
> +Если передать название `css` свойства, то результатом будет его значение, если же передать массив названий - результатом будет объект `{key:value}`
Дубль текста из пункта "Типы"

2023-08-08 11:18 UTC, BagenovA commented on src/hooks/useStyleProps/__stand__/useStyleProps.stand.tsx
> +  description: 'Хук для получения переменых элемента.',
Исправить опечатку в слове "переменных"

2023-08-08 11:18 UTC, BagenovA commented on src/hooks/useThemeVars/__stand__/useThemeVars.stand.mdx
> +и размер шрифта зависит от ширины экрана, тогда вам нужно прописать в `useThemeVars` текущую граничную точку (breakpoint) как зависимость.
Может заменить "граничную точку" на "контрольную точку"?

2023-08-10 14:31 UTC, gizeasy commented on src/hooks/useStyleProps/__stand__/useStyleProps.stand.mdx
> +Если передать название `css` свойства, то результатом будет его значение, если же передать массив названий - результатом будет объект `{key:value}`
Потому что оно там также работает и это надо указать))

2023-08-10 14:49 UTC, merged