fix(TextField): fix clear button
consta-design-system/uikit pull request #3199
Opened 2023-08-07 08:27 UTC by N1MBER

closes #3178

2023-08-08 11:42 UTC, hell0anna commented
<img width="319" alt="image" src="https://github.com/consta-design-system/uikit/assets/51019093/26c0aecb-ed68-4d83-8565-6fb9492a35fe">
неверный цвет кнопки, по дизайну идет control-default/typo-placeholder

2023-08-08 11:57 UTC, gizeasy requested changes
см. коменты

2023-08-10 13:47 UTC, gizeasy requested changes

2023-08-10 13:47 UTC, gizeasy commented on src/components/TextField/TextField.tsx
>                className={cnTextField('ClearButton')}
Проставь tabIndex чтобы не фокусилась кнопка с крестиком по табу

2023-08-16 10:46 UTC, merged