feat(withDefaultProps): add new hoc
consta-design-system/uikit pull request #3214
Opened 2023-08-17 12:08 UTC by N1MBER

closes #3137

2023-08-17 16:08 UTC, BagenovA requested changes

2023-08-17 16:08 UTC, BagenovA commented on src/hocs/withDefaultProps/__stand__/withDefaultProps.stand.mdx
> +При помощи хока `withDefaultProps` можно создать компонент, который будет иметь определенные по умолчанию свойства.
Может так: С помощью хока `withDefaultProps` можно создать компонент со свойствами по умолчанию.

2023-08-17 16:08 UTC, BagenovA commented on src/hocs/withDefaultProps/__stand__/withDefaultProps.stand.mdx
> +Первым аргументом хок принимает компонент, а вторым те свойства которые вы хотите определить по умолчанию.
Можно так: Первым аргументом хок принимает компонент, а вторым те свойства, которые вы определите по умолчанию.

2023-08-18 09:38 UTC, gizeasy requested changes
Давай пока остановим прку, с дженериками за хуком проблемы

2023-08-18 09:38 UTC, gizeasy commented on src/hocs/withDefaultProps/withDefaultProps.tsx
> +};
export const withDefaultProps = <
  COMPONENT_TYPE extends JSXElementConstructor<any>,
>(
  component: COMPONENT_TYPE,
  defaultProps?: React.ComponentProps<COMPONENT_TYPE>,
): COMPONENT_TYPE => {
  const Wrapper = (props: any, ref: any) => {
    const Component = component;

    return <Component ref={ref} {...(defaultProps ?? {})} {...props} />;
  };

  return Wrapper as unknown as COMPONENT_TYPE;
};

2023-09-20 12:36 UTC, closed without merging