feat(BookmarkTabs): add new component
consta-design-system/uikit pull request #3224
Opened 2023-08-23 14:41 UTC by N1MBER

2023-08-28 08:19 UTC, gizeasy requested changes
https://refs-pull-3224-merge---uikit.consta.design/libs/uikit/components-bookmarktabs-canary/dev?hash=%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%B8

скачут элементы при перестроении в фит мод

2023-08-28 08:31 UTC, gizeasy requested changes

2023-08-28 08:31 UTC, gizeasy commented on src/components/BookmarkTabsCanary/BookmarkTabs.css
> +.BookmarkTabs {
Не получается сколлить табы нативно с тачпада

2023-08-28 08:31 UTC, gizeasy commented on src/components/BookmarkTabsCanary/useBookmarkTabs.ts
> +  const wrapperRef = useRef<HTMLDivElement>(null);
const [wrapperRef, containerRef, fixedTabsRef, otherTabsRef] = useRefs<HTMLDivElement>(4);
можно так

2023-08-28 08:31 UTC, gizeasy commented on src/components/BookmarkTabsCanary/useBookmarkTabs.ts
> +  const controlSize = size === 'm' ? 40 : 32;
не факт что размер будети таким, в теме могут поменять спейсы и приехали

2023-08-28 08:31 UTC, gizeasy commented on src/components/BookmarkTabsCanary/useBookmarkTabs.ts
> +  const { width: containerWidth } = useComponentSize(containerRef);
useComponentSize конечно подходит но он создает несколько подписок, в том случяае когда элементы будут одновременно менять рамеры компонент будет 2 или 3 раза обновлятся, можно оптимизировать этот момент и сделать через ResizeObserver, он будет следить за каждым элементом и при изменении любого производить расчеты, ели изменились сразу 2 то расчет будет производится 1 раз

2023-08-30 15:40 UTC, BagenovA approved these changes

2023-08-30 16:13 UTC, merged