feat(DatePicker): add new props: dropdownOpen, onDropdownOpen, ignoreOutsideClicksRefs
consta-design-system/uikit pull request #3238
Opened 2023-08-31 13:14 UTC by N1MBER

closes #3090

2023-09-05 08:18 UTC, gizeasy requested changes
Не работает управление с клавиатуры
https://github.com/consta-design-system/uikit/issues/3090

2023-09-05 09:20 UTC, BagenovA requested changes

2023-09-05 09:20 UTC, BagenovA commented on src/components/DatePicker/__stand__/DatePicker.dev.stand.mdx
> +- [Управление состоянием выподающего списка](#управление-состоянием-выподающего-списка)
Исправить опечатку в слове "выпадающего"

2023-09-05 09:20 UTC, BagenovA commented on src/components/DatePicker/__stand__/DatePicker.dev.stand.mdx
> +## Управление состоянием выподающего списка
Исправить опечатку в слове "выпадающего"

2023-09-05 09:20 UTC, BagenovA commented on src/components/DatePicker/__stand__/DatePicker.dev.stand.mdx
> +Для управлением состояния выподающего списка используйте следующие свойства:
Лучше так: Для управления состоянием выпадающего списка используйте следующие свойства

2023-09-05 09:20 UTC, BagenovA commented on src/components/DatePicker/__stand__/DatePicker.dev.stand.mdx
> +- `ignoreOutsideClicksRefs` - список ссылок на элементы по которым игнорируется клики
Лучше так: список ссылок на элементы по которым игнорируются клики

2023-09-05 09:20 UTC, BagenovA commented on src/components/DatePicker/__stand__/DatePicker.dev.stand.mdx
> +| [`dropdownOpen?` ](#управление-состоянием-выподающего-списка)                              | `boolean`
Исправить опечатку в слове "выпадающего"

2023-09-05 09:20 UTC, BagenovA commented on src/components/DatePicker/__stand__/DatePicker.dev.stand.mdx
> +| [`ignoreOutsideClicksRefs?`](#управление-состоянием-выподающего-списка)                    | `ReadonlyArray<React.RefObject<HTMLElement>>`
Лучше так: Ссылки на элементы, которые нужно игнорировать при кликах вне компонента

2023-09-05 09:35 UTC, gizeasy commented on src/hooks/useKeysRef/useKeysRef.ts
> +export const useKeysRef = (
А чем прямое взаимодействие в JSX не понравилось?

я тут для чипсов тоже хук сделал

```tsx
import { useCallback } from 'react';

import { useMutableRef } from '##/hooks/useMutableRef';
import { KeyCode } from '##/utils/types/KeyCode';

type KeyHandlers = Partial<Record<KeyCode, React.KeyboardEventHandler>> & {
  [key: string]: React.KeyboardEventHandler;
};

type UseKeysProps = {
  keys: KeyHandlers;
  onEvent?: React.KeyboardEventHandler;
  isActive: boolean;
};

export const getKeyHandler = (
  keys: KeyHandlers,
): React.KeyboardEventHandler => {
  return (e: React.KeyboardEvent) => {
    (keys[e.code as KeyCode] || keys[e.key as KeyCode])?.(e);
  };
};

export const useKeys = (props: UseKeysProps): React.KeyboardEventHandler => {
  const propsRef = useMutableRef(props);
  return useCallback((e) => {
    const { isActive, keys, onEvent } = propsRef.current;
    if (isActive) {
      getKeyHandler(keys)(e);
    }
    onEvent?.(e);
  }, []);
};
```

вызов такой

```tsx
const onKeyUp = useKeys({
    keys: {
      Enter: () => {
        iconButtonRef.current?.focus();
      },
      Escape: () => {
        componentRef.current?.focus();
      },
    },
    onEvent: onKeyUpProp,
    isActive: Boolean(iconButtonRef && onRightIconClick),
  });
```

В моем случае можно полученную функцию подсунуть на любое событие `onKeyUp` | `onKeyDown`

2023-09-06 14:55 UTC, gizeasy approved these changes

2023-09-06 14:55 UTC, merged