feat(Loader): rewrite styles and layout
consta-design-system/uikit pull request #3239
Opened 2023-08-31 13:35 UTC by N1MBER

closes #2650

2023-09-01 07:20 UTC, gizeasy requested changes
Давай новый LoaderCanary  создадим, чтобы не афектить текущие проекты

2023-09-05 09:07 UTC, BagenovA approved these changes

2023-09-05 09:22 UTC, gizeasy requested changes

2023-09-05 09:22 UTC, gizeasy commented on src/components/LoaderCanary/Loader.css
> +
Рутовый размер лодера должен быть с учетом размеров анимации, иначе кружечки выходя за его края

2023-09-06 10:58 UTC, merged