feat(ContextMenu): add keyboard navigation
consta-design-system/uikit pull request #3259
Opened 2023-09-08 09:45 UTC by N1MBER

closes #3250

2023-09-08 14:12 UTC, gizeasy requested changes

2023-09-08 14:12 UTC, gizeasy commented on src/components/ContextMenu/useMenuNavigation.ts
> +  const onKeyDown = (e: React.KeyboardEvent) => {
Кажется нужно предотвращать всплытие иначе по стрелкам скролится страница.

Управление через клавишам не работает при IsMobile

2023-09-13 07:46 UTC, gizeasy requested changes

2023-09-13 07:46 UTC, gizeasy commented on src/components/ContextMenu/useMenuNavigation.ts
> +export const useMenuNavigation = (props: UseMenuNavigationProps) => {
Давай при наведении на элемент, менять состояние activeIndex, отключим hover effect и таким образом у нас ховер и фокус отвечают одновременно за активность элемента.

2023-09-13 07:46 UTC, gizeasy commented on src/components/ContextMenu/useMenuNavigation.ts
> +  const refs = useRefs<HTMLDivElement>(items.length);
Сейчас при открытии сразу  выделяется первый пункт, давай поставим изначальный индекс (-1) и при нажатия на клавиши up down ставить индекс 0

2023-09-18 10:23 UTC, gizeasy requested changes
1) При возвращении на предыдущий с клавиатуры, логичнее всего подсвечивать тот пункт меню которого только что закрыли

2) Ховер надо пофиксисть

https://github.com/consta-design-system/uikit/assets/13190808/1ef2f06f-fefd-498c-921a-cb38ba9deb70

2023-09-20 11:54 UTC, gizeasy reviewed
Слушай, а закрывать меню по Esc, предпологаем что с верху делать будем?

2023-09-27 07:17 UTC, gizeasy requested changes
Нужно сделать закрытие по Esc и после этого зафокусить якорь
также не работает управление с клавиатуры при isMobile

2023-09-27 11:54 UTC, BagenovA approved these changes

2023-09-27 14:04 UTC, gizeasy requested changes
При isMobile переходы вперед с клавиатуры отображатся с рваной анимацией

2023-10-04 12:59 UTC, merged