feat(MixFlex): add new mixin
consta-design-system/uikit pull request #3294
Opened 2023-09-20 15:22 UTC by N1MBER

closes #3291

2023-09-25 10:41 UTC, BagenovA requested changes

2023-09-25 10:41 UTC, BagenovA commented on src/mixs/MixFlex/__stand__/MixFlex.stand.mdx
> +Миксин `MixFlex` делает из элемента, на котором он применяется - flex-контейнер.
Может так: Миксин `MixFlex` делает из элемента, в котором он используется, flex-контейнер.

2023-09-25 10:41 UTC, BagenovA commented on src/mixs/MixFlex/__stand__/MixFlex.stand.tsx
> +  alias: ['миксин', 'контейнер', 'флекс', 'лаяут', 'положение', 'flex'],
Предлагаю заменить "лаяут" на "лейаут"

2023-09-27 07:20 UTC, gizeasy reviewed
А кто-то это просил? Я вот думаю надо ли мне такое, и больше склоняюсь к тому что не надо. Ты из своего проекта его перенес?

2023-09-27 09:02 UTC, N1MBER commented
> А кто-то это просил? Я вот думаю надо ли мне такое, и больше склоняюсь к тому что не надо. Ты из своего проекта его перенес?

Да, я его часто использую, потому что часто нужно сделать простой компонент, и если его стили это чисто флексы, то можно через миски все сделать и не создавать css-ку. По факту тут такой же кейс как и с MixSpace, можно спокойно и без него жить

2023-09-29 10:25 UTC, merged