feat(BookmarkTabs): rewrite hover and focus to highlitedIndex
consta-design-system/uikit pull request #3333
Opened 2023-10-05 09:46 UTC by N1MBER

closes #3233

2023-10-05 21:00 UTC, BagenovA requested changes

2023-10-05 21:00 UTC, BagenovA commented on src/components/BookmarkTabsCanary/__stand__/BookmarkTabs.dev.stand.mdx
>  - `as` - HTML-тег ренедера;
Исправить опечатку в слове "рендера"

2023-10-06 08:48 UTC, gizeasy requested changes

2023-10-06 08:48 UTC, gizeasy commented on src/components/BookmarkTabsCanary/BookmarkTabsCanary.tsx
> +    onMouseLeaveProp?.(e);
onMouseLeaveProp пользовательский `onMouseLeave` не запускается

2023-10-06 08:48 UTC, gizeasy commented on src/components/BookmarkTabsCanary/BookmarkTabsCanary.tsx
> +        controlRef,
Слушай а может рефку уже и не отдавать в рендер а накидывать на врапер,

2023-10-06 08:48 UTC, gizeasy commented on src/components/BookmarkTabsCanary/BookmarkTabsCanary.tsx
> +        tabRef: getItemRef(item),
А зачем tabRef и отдельно controlRef?

2023-10-06 11:07 UTC, N1MBER commented on src/components/BookmarkTabsCanary/BookmarkTabsCanary.tsx
> +        controlRef,
Лучше tabref передавать в рендер функцию, чтоб ее вешали на таб непосредственно

2023-10-06 11:30 UTC, gizeasy commented on src/components/BookmarkTabsCanary/BookmarkTabsCanary.tsx
> +        controlRef,
почему? зачем?

2023-10-23 11:49 UTC, gizeasy approved these changes

2023-10-23 11:49 UTC, merged