feat(TooltipCanary): added canary tooltip with animations
consta-design-system/uikit pull request #3334
Opened 2023-10-05 11:22 UTC by N1MBER

closes #3303

2023-10-05 11:22 UTC, N1MBER commented
Андрюх, как глянешь напиши мне, я добавлю его во все использующие тултип компоненты

2023-10-05 21:13 UTC, BagenovA requested changes

2023-10-05 21:13 UTC, BagenovA commented on src/components/TooltipCanary/Tooltip.css
> +  /* Фон отдельным элементом, чтобы можно было добавить ему opacity */
Может так: Фон сделать отдельным элементом, чтобы можно было использовать свойство opacity

2023-10-05 21:13 UTC, BagenovA commented on src/components/TooltipCanary/__stand__/Tooltip.dev.stand.mdx
> +За размер тултипа отвечает свойство `size`. Варианты: `s`, `m`, `l`. В зависимости от выбранного размера изменятеся максимальная ширина тултипа.
Исправить опечатку в слове "изменяется"

2023-10-05 21:13 UTC, BagenovA commented on src/components/TooltipCanary/__stand__/Tooltip.dev.stand.mdx
> +Иногда может быть полезно дополнительно выделить статус сообщения в nултипе, например для сообщения об ошибке. Сделать это можно с помощью свойства `status` со значениями: `normal`, `success`, `warni
Может так: Иногда можно дополнительно выделить статус сообщения в тултипе, например для уведомления об ошибке.

2023-10-06 09:25 UTC, gizeasy approved these changes

2023-10-23 11:34 UTC, merged