feat(PaginationCanary): added new canary component
consta-design-system/uikit pull request #3355
Opened 2023-10-16 19:22 UTC by N1MBER

closes #2892

2023-10-16 20:52 UTC, BagenovA requested changes

2023-10-16 20:52 UTC, BagenovA commented on src/components/PaginationCanary/__stand__/Pagination.dev.stand.mdx
> +В случаях когда вы не хотите отоброжать все страницы сразу вы можете рендерить только необходимое вам количество, задаваемое через `visibleCount`.
Может так: Чтобы не отображать все страницы сразу, можно рендерить только необходимое их количество, задаваемое через `visibleCount`.

2023-10-16 20:52 UTC, BagenovA commented on src/components/PaginationCanary/__stand__/Pagination.dev.stand.mdx
> +Если у вас большое количество страниц и вы хотите дать пользователю видеть количство страниц и дать перходить на первую и последняю укажите свойства `showFirstPage` и `showLastPage` соответственно.
Может так: Чтобы пользователь видел количество страниц и мог переходить на первую и последнюю из них, укажите свойства `showFirstPage` и `showLastPage` соответственно.

2023-10-16 20:52 UTC, BagenovA commented on src/components/PaginationCanary/__stand__/Pagination.dev.stand.mdx
> +Для того чтобы отобразить кнопки перехода в конец или начало определите свойство `outerMostArrows`. Оно принимает массив двух значений, где может быть:
Может так: Чтобы отобразить кнопки перехода в конец или начало, определите свойство `outerMostArrows`. Оно принимает массив двух значений, где может быть:

2023-10-16 20:52 UTC, BagenovA commented on src/components/PaginationCanary/__stand__/Pagination.dev.stand.mdx
> +Для того чтобы отобразить кнопки для перехода по страницам вперед назад определите свойство `arrows`. Оно принимает массив двух значений, где может быть:
Можно так: Чтобы отобразить кнопки для перехода по страницам вперед или назад, определите свойство `arrows`. Оно принимает массив двух значений, где может быть:

2023-10-16 20:52 UTC, BagenovA commented on src/components/PaginationCanary/__stand__/Pagination.dev.stand.mdx
> +Вы можете установить клавиши, с которыми пользователи смогут переключать страницы. Обычно для этого используют **Control** со стрелками.
Можно так: Вы можете установить клавиши быстрого переключения страниц. Обычно для этого используют **Control** со стрелками.

2023-10-16 20:52 UTC, BagenovA commented on src/components/PaginationCanary/__stand__/Pagination.dev.stand.mdx
> +- `as?` - HTML-тег ренедера;
Исправить опечатку в слове "рендера"

2023-10-16 20:52 UTC, BagenovA commented on src/components/PaginationCanary/__stand__/Pagination.dev.stand.mdx
> +| `getItemOnClick?`                       | `PaginationPropGetItemOnClick`                                           | -            | Функция для получения события нажатя на элемент
Исправить опечатку в слове "нажатия"

2023-10-16 20:52 UTC, BagenovA commented on src/components/PaginationCanary/__stand__/Pagination.stand.mdx
> +Компонент `Pagination` позволяет пользователю выбрать конкретную страницу из диапазона страниц
Может так: С помощью компонента `Pagination` можно выбрать конкретную страницу из диапазона и перейти к ней.

2023-10-16 20:52 UTC, BagenovA commented on src/components/PaginationCanary/__stand__/Pagination.stand.tsx
> +  description: 'Пагинация. Можно выбрать страницу.',
Может так: Пагинация. Компонент для нумерации страниц и их выбора

2023-10-16 20:52 UTC, BagenovA commented on src/components/PaginationCanary/helpers.ts
> +  const delta = 2; // Количество элементов которое нужно пройти чтоб появилось многоточие
Может так: Количество элементов, которое нужно пройти для появления многоточия

2023-10-23 12:20 UTC, gizeasy requested changes
1) при очистки поля ввода появляется `0` и курсор передвигается в начало, что в дальнейшем услажняет ввод
2) если курсор стоит в поле то по клавишам влево/вправа курсор не передвигается, а происход всплытие события и переключаются страницы
3) В кнопках страниц не вмещается больше чем 3 символа, надо предусматреть растягивания блока, а в размере xs сильно маленькие отступы. Надо пообщатся с дизанерами найти решние.
4) Надо спросить у дизайнеров а выбранный пункт по возможности должен отображаться в срередине? Мне кажется что надо в середине
5) При type=input очень маленькое растояние между кнопками и инпутом, от этого фокус эфект от коки соприкасается с инпутом, выглядит как не доработка
6) Думаю что кнопки страниц тоже нужно сделать с фокус эффектом
7) Надо вместе с дизайнерами подумать об управлении с клавиатуры.

2023-10-25 08:15 UTC, gizeasy commented
на стенде
showFirstPage и showLastPage должны отображаться только при type=default

2023-10-25 11:41 UTC, gizeasy requested changes

2023-10-25 11:41 UTC, gizeasy commented on src/components/PaginationCanary/usePaginationItems.tsx
> +  const { width: firstWidth } = useComponentSize(firstButtonRef);
лучше сделай через useResizeObserved, в него какраз можно передать массив рефок, и функцию мапера которая вернет только ширину, в итоге получется 



```
const refs = useRefs(5)
const [firstWidth,prevWidth,nextWidth,lastWidth,width] = useResizeObserved(refs, getElementSize)
```

2023-10-25 11:41 UTC, gizeasy commented on src/components/PaginationCanary/usePaginationItems.tsx
> +  const { prevButtonRef, nextButtonRef } = usePaginationKeys({
usePaginationKeys пусть не возвращает рефки а просто получает и навешивает на них собития.

2023-10-25 11:41 UTC, gizeasy commented on src/components/PaginationCanary/usePaginationItems.tsx
> +  const wrapperRef = useRef<HTMLDivElement>(null);
все рефки можешь создать через useRefs

2023-10-25 12:04 UTC, N1MBER commented
Отмечать по середине активный элемент

2023-11-07 13:32 UTC, gizeasy requested changes

2023-11-07 13:32 UTC, gizeasy commented on src/components/PaginationCanary/PaginationNumberInput/PaginationNumberInput.tsx
> +  const handleKeyDown: React.KeyboardEventHandler = useCallback(
также пользователь может нажимать кнопки вверх и вниз и сейчас в поле значение меняется но onChange не отрабатывает, те. value не меняется. Надо исправить

2023-11-13 09:33 UTC, gizeasy requested changes

2023-11-13 09:33 UTC, gizeasy commented on src/components/PaginationCanary/types.ts
> +export type PaginationPropOuterMostArrow = boolean | IconComponent;
Слушай, а по чему у стрелок назад/вперед тип отличается

export type PaginationPropArrow =
  | boolean
  | IconComponent
  | {
      label?: string;
      disabled?: boolean;
      icon?: IconComponent;
    };

Разве не нужно указать кнопку лейблом? Или за дизеблить приенудительно?
А вообще зачем нужен disabled на кнопку?

2023-11-14 09:18 UTC, gizeasy requested changes
Опиши пожалуйста нюансы с адоптивностью, какойе минимальное количиство отображаемых пунктов, и что делать если не влазит.

По хорошему сделать пример с полоской которую можно туда сьда двигать и смотреть как изменяется компонент. также в примере заюзай хук useComponentBreakpoint чтобы показать как включать выключать парамерты в зависимости от ширины контейнера

2023-11-14 09:19 UTC, merged