feat(Attachment): add new prop 'withIcon'
consta-design-system/uikit pull request #3374
Opened 2023-10-30 09:01 UTC by N1MBER

closes #3370

2023-11-02 12:55 UTC, BagenovA requested changes

2023-11-02 12:55 UTC, BagenovA commented on src/components/AttachmentCanary/__stand__/Attachment.use.stand.mdx
> +На первый взгляд внешне это состояние не отличается от предыдущего. Разница в том, что тут нет никаких кнопок, так как с самим файлом уже нельзя ничего сделать. В этом случае компонент должен стать с
Может так: На первый взгляд, это состояние не отличается от предыдущего.

2023-11-07 13:23 UTC, gizeasy requested changes

2023-11-07 13:23 UTC, gizeasy commented on src/components/AttachmentCanary/types.ts
> +  withIcon?: boolean;
Думаю что надо Icon переименовать, может в Pictogram -> `withPictogram`

2023-11-10 08:46 UTC, merged