feat(TextField): update mask
consta-design-system/uikit pull request #3375
Opened 2023-10-30 14:50 UTC by gizeasy

BREAKING CHANGE: update imask to v7, remove our useIMask

fix #3139

2023-10-30 16:26 UTC, N1MBER approved these changes

2023-11-02 12:36 UTC, BagenovA requested changes

2023-11-02 12:36 UTC, BagenovA commented on src/components/DatePicker/DatePickerFieldTypeDate/helpers.ts
> -      // если количество введенных символов меньше чем в формате маски
Может так:

       // если количество введенных символов меньше, чем в формате маски,
      // то не нужно мешать вводу с клавиатуры
      // если дата была введена полностью и value пришел null,
      // то можно считать, что поле нуждается в очистке

2023-11-02 12:36 UTC, BagenovA commented on src/components/TextField/__stand__/TextField.dev.stand.mdx
> +Для того чтобы использовать маски вместе с компонентом `TextField` необходимо импортировать хук [useIMask](https://github.com/uNmAnNeR/imaskjs/tree/master/packages/react-imask#using-hook).
Добавить запятую: "Для того, чтобы..."

2023-11-02 12:36 UTC, BagenovA commented on src/components/TextField/__stand__/TextField.dev.stand.mdx
> +Для того чтобы указать значение в момент первого рендера используйте `defaultValue`.
Может так:

Для того, чтобы указать значение в момент первого рендера, используйте `defaultValue`.
Для того, чтобы изменить поле программно, используйтете `setValue` из хука.

2023-11-02 12:36 UTC, BagenovA commented on src/components/TextField/__stand__/TextField.dev.stand.mdx
> +        label="Пасспорт"
Исправить опечатку в слове "паспорт"

2023-11-07 13:25 UTC, merged