Feat/drag n drop field canary
consta-design-system/uikit pull request #3600
Opened 2024-04-04 13:26 UTC by Elena-BLZ

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2024-04-05 06:45 UTC, gizeasy requested changes
PR назван не по шаблону.
Не подвязан issue к PR

2024-04-05 09:11 UTC, gizeasy requested changes
PR назван не по шаблону.
Не подвязан issue к PR

2024-04-05 09:11 UTC, gizeasy commented on src/components/DragNDropFieldCanary/DragNDropFieldCanary.tsx
> +          <Text view="secondary" size="s" align="center" lineHeight="m">
Может вообще сделать только renderProps, кажется это будет самое удобное.
И перенести вывод текста "Перетащите файлы сюда" в DragNDropFieldContent.

2024-04-05 09:11 UTC, gizeasy commented on src/components/DragNDropFieldCanary/DragNDropFieldContent/formatFileRequirements.ts
> +// const formatAccept = (
не нужный коментарий

2024-04-05 09:11 UTC, gizeasy commented on src/components/DragNDropFieldCanary/DragNDropFieldInformer/DragNDropFieldInformer.tsx
> +// eslint-disable-next-line no-unused-vars
А что там не используется, может удалить?

2024-04-05 09:11 UTC, gizeasy commented on src/components/DragNDropFieldCanary/DragNDropFieldInformer/DragNDropFieldInformer.tsx
> +      ) : (
Давай не вложенным условием а 

```tsx
{!loading && Icon && (<Icon/>)}
```

2024-04-05 09:11 UTC, gizeasy commented on src/components/DragNDropFieldCanary/DragNDropFieldInformer/Informer.css
> +.Informer {
названия компонетов и их классов должны совпадать, переименуй в  DragNDropFieldInformer

2024-04-05 09:45 UTC, Elena-BLZ commented on src/components/DragNDropFieldCanary/DragNDropFieldInformer/DragNDropFieldInformer.tsx
> +// eslint-disable-next-line no-unused-vars
key

2024-04-05 10:20 UTC, Elena-BLZ commented on src/components/DragNDropFieldCanary/DragNDropFieldCanary.tsx
> +      locale: localeProp,
Нужно не только для ошибок, но и для DragNDropFieldContent, чтобы локализовать требования

2024-04-08 09:56 UTC, gizeasy requested changes

2024-04-18 09:27 UTC, gizeasy requested changes

2024-04-25 12:08 UTC, alyonurchick1 commented
Давайте изменим подпись в конструкторе. Оставим только "Перетащите файлы сюда или загрузите по кнопке"
![image](https://github.com/consta-design-system/uikit/assets/121174918/c6715b92-799a-4f9e-b6a2-d27937489def)
И еще момент: в примере по умолчанию написано просто "Подходят файлы", кажется так не должно быть. Но в юбом случае давайте оставим опять-таки только "Перетащите файл сюда или загрузите по кнопке"
![image](https://github.com/consta-design-system/uikit/assets/121174918/7bbc6bed-73f3-4e2e-9faf-dd8a8170dfb1)

Почему так: пользователь может настроит колбеки, чтобы возвращалась инфа о том, что так/не так с файлами, прописывать в поле отдельные форматы не очень хорошо с точки зрения UX, как мне кажется.

2024-04-25 12:50 UTC, alyonurchick1 commented
Еще в примерах часто встречается импорт вида:
`import {
  DragNDropField,
  DragNDropFieldPropLocale,
  getErrorsList,
} from '@consta/uikit/DragNDropField';`
Точно импорт из `DragNDropField`, а не `DragNDropFieldCanary`?

2024-04-25 13:53 UTC, alyonurchick1 requested changes

2024-04-25 13:53 UTC, alyonurchick1 commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.dev.stand.mdx
> +import { DragNDropFieldCanary } from '@consta/uikit/DragNDropFieldCanary';
Проверь, пж, верный ли здесь импорт

2024-04-25 13:53 UTC, alyonurchick1 commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.dev.stand.mdx
> +import { DragNDropField } from '@consta/uikit/DragNDropField';
Проверь корректность импорта, пж

2024-04-25 13:53 UTC, alyonurchick1 commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.dev.stand.mdx
> +import {
Проверь корректность импорта, пж

2024-04-25 13:53 UTC, alyonurchick1 commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.dev.stand.mdx
> +import { DragNDropFieldInformer } from '@consta/uikit/DragNDropField';
Проверь корректность импорта, пж

2024-04-25 13:53 UTC, alyonurchick1 commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.stand.mdx
> +import { DragNDropFieldCanary } from '@consta/uikit/DragNDropFieldCanary';
и здесь

2024-04-25 13:53 UTC, alyonurchick1 commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.stand.tsx
> +  figma:
Ждем, когда Леша зарелизит в дизайне

2024-04-25 15:54 UTC, gizeasy requested changes

2024-04-25 15:54 UTC, gizeasy commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.dev.stand.mdx
> +> Чтобы использовать компонент, обновите библиотеку [react-dropzone](https://react-dropzone.js.org/?ref=blog.horizon-ui.com).
До версии `^14.2.3`

2024-04-25 15:54 UTC, gizeasy commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.dev.stand.mdx
> +import { DragNDropFieldCanary } from '@consta/uikit/DragNDropFieldCanary';
`import { DragNDropField } from '@consta/uikit/DragNDropFieldCanary';`

2024-04-25 15:54 UTC, gizeasy commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.dev.stand.mdx
> +  - [Максимальный и минимальный размер](#максимальный-и-минимальный-размер)
Ссылка ни куда не ведет

2024-04-25 15:54 UTC, gizeasy commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.dev.stand.mdx
> +| `gigabyte` | `string` | `Гб`         |
```
| `gigabyte` | `string` | `'Гб'`         |
```
Разница в том что `'Гб'` это строка, а  `Гб` переменная
| `gigabyte` | `string` | `'Гб'`         |

2024-04-25 15:54 UTC, gizeasy commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.dev.stand.mdx
> +    onDropRejected?: (
отступы слева лишние

2024-04-25 15:54 UTC, gizeasy commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.dev.stand.mdx
> +    onError?: (err: Error) => void;
отступ слева лишний

2024-04-25 15:54 UTC, gizeasy commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.dev.stand.mdx
> +import { DragNDropField } from '@consta/uikit/DragNDropField';
import { DragNDropField } from '@consta/uikit/DragNDropFieldCanary';

2024-04-25 15:54 UTC, gizeasy commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.dev.stand.mdx
> +import {
@consta/uikit/DragNDropFieldCanary

2024-04-25 15:54 UTC, gizeasy commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.dev.stand.mdx
> +import { DragNDropFieldInformer } from '@consta/uikit/DragNDropField';
@consta/uikit/DragNDropFieldCanary

2024-04-25 15:54 UTC, gizeasy commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.stand.mdx
> +import { DragNDropFieldCanary } from '@consta/uikit/DragNDropFieldCanary';
import { DragNDropField } from '@consta/uikit/DragNDropFieldCanary';

2024-04-25 15:54 UTC, gizeasy commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.dev.stand.mdx
> +```tsx
тут ts, tsx - в тех случаях где видишь html(jsx) разметку

И во всех примерах проверь плиз

2024-04-25 15:54 UTC, gizeasy commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.stand.tsx
> +  sandbox: 'dragndropfield-gst04t',
Удалить кодсанбоксовкий id

2024-04-25 15:54 UTC, gizeasy commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.stand.tsx
> +  version: '2.1.0',
версию указать 5.3.0

2024-04-25 15:54 UTC, gizeasy commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.stand.tsx
> +    'https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?type=design&node-id=32774-0&mode=design',
Ссылка фигмы ведет кудато ни туда

2024-04-25 15:54 UTC, gizeasy commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.dev.stand.mdx
> +import {
Импорты примеров есть но сами примеры не используются

Вообще жалко что некоторые крутые примеры вообще не описаны, к примеру пример с загрузкой картинок в квадратиках а сам драгндропфилд это квадрат с плюсиком

2024-04-25 15:54 UTC, gizeasy commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.dev.stand.mdx
> +import {
Завел задачку https://github.com/consta-design-system/uikit/issues/3646

2024-04-25 15:54 UTC, gizeasy commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.dev.stand.mdx
> +| Свойство                                             | Тип                                                                                   | Описание
А почему тут отсутствует слобеу по умолчанию хотя свойства по умолчанию присутствуют. Кажется что подобные таблицы стоит делать однообразными для более простой читабельности

если дело в том что тип занимает много места можно сами типы описать выше таблицы и ссылатся на них из таблицы

2024-04-25 15:54 UTC, gizeasy commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.dev.stand.mdx
> +| `call-to-action`      | `LocaleLabel` &#124; `string` | `Перетащите файл сюда или загрузите по кнопке`                                             | Основной текст в окне компонента
LocaleLabel не описан в документации

2024-04-25 15:54 UTC, gizeasy commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.dev.stand.mdx
> +Чтобы локализовать компонент, используйте свойство `locale: DragNDropFieldPropLocale`.
DragNDropFieldPropLocale не описан в документации

2024-04-25 17:14 UTC, alyonurchick1 commented on src/components/DragNDropFieldCanary/__stand__/DragNDropField.dev.stand.mdx
> +| Свойство                                             | Тип                                                                                   | Описание
Я убрала столбец "по умолчанию", потому что он был не информативный: только у свойства multiple было указано значение по умолчанию "false", перенесла эту же инфу в столбец "Описание".  Вообще ориентировалась на то, что в доках не делают отдельный столбец для значений по умолчанию, а выносят в соседний (отличный пример в [доке стримлита](https://docs.streamlit.io/develop/api-reference/widgets/st.file_uploader). Помимо этого этот столбец съедает много места и более важный столбец "Описание" становится менее заметным. 
 
Не поняла про описание типов выше. Мне кажется, стоит рассмотреть вариант упразднения столбца "По умолчанию" на более масштабном уровне и перенести значения из него в описание.

2024-04-26 13:42 UTC, gizeasy approved these changes

2024-04-26 13:46 UTC, merged