docs(ContextMenu): how-to-use
consta-design-system/uikit pull request #3665
Opened 2024-05-27 07:40 UTC by alyonurchick1

closes consta-design-system/uikit#3634

2024-05-27 12:42 UTC, gizeasy requested changes

2024-05-27 12:42 UTC, gizeasy commented on src/components/ContextMenu/__stand__/images/Frame3.image.svg
Изображения имеют разные отступы от краев, кажется что их лучше вовсе убрать и рулить css'ом, Так же сильно избыточно рендерить SVG, давайте возмем png. с x2 x3 разрешением, и отрисуем их через компонент Picture, который сделан как раз для того чтобы чтобы рисовать нужную в зависимости от DPI монитора картинку.

Так же можно вообще взять jpg картинки для разных тем и также рисовать их через компонент Picture

2024-08-27 12:17 UTC, gizeasy approved these changes

2024-08-29 14:03 UTC, merged

2024-09-12 17:37 UTC, alyonurchick1 commented on src/components/ContextMenu/__stand__/ContextMenu.use.stand.mdx
> +import start_example from './images/ContextMenu_example_08.jpg';
@gizeasy Почему было решено заменить названия картинок? Я специально создавала "говорящие" названия, чтобы можно было менять/удалять/обновлять картинки, не открывая каждую отдельно