docs(Tag): how-to-use
consta-design-system/uikit pull request #3674
Opened 2024-06-03 19:12 UTC by alyonurchick1

closes consta-design-system/uikit#3633

2024-06-05 20:33 UTC, alyonurchick1 reviewed
@linturaven , проведи ревью, пожалуйста и посмотри комменты

2024-06-05 20:33 UTC, alyonurchick1 commented on src/components/Tag/__stand__/Tag.use.stand.mdx
> +<MdxImage src={book} />
Это просто референс. Хочется картинку с той же сутью, но нашим дизайном

2024-06-05 20:33 UTC, alyonurchick1 commented on src/components/Tag/__stand__/Tag.use.stand.mdx
> +- **Иконки для наглядности**. [Добавление иконок](##LIBS.LIB.STAND.TAB/lib:uikit/stand:components-tag-stable/tab:dev/hash:иконка) рядом с текстом тега может улучшить восприятие информации. Иконка дол
Тоже хочется цельного примера с иконками

2024-06-05 20:33 UTC, alyonurchick1 commented on src/components/Tag/__stand__/Tag.use.stand.mdx
> +<MdxImage src={group} />
Пожалуйста, настрой svg так, чтобы: 
1. Контрастно выглядело при смене темы 
2. Края были обработаны так, чтобы выглядело ок при импорте в док. Это к комментарию Андрея здесь https://github.com/consta-design-system/uikit/pull/3665#discussion_r1615991794

2024-06-05 20:33 UTC, alyonurchick1 commented on src/components/Tag/__stand__/Tag.use.stand.mdx
> +<MdxImage src={chips} />
Нужна картинка с вариантом использования чипсов. Её же потом добавим в "Как использовать" чипсов. Все рандомные png, которые встречаются в "Как использовать" - это мои кровью и потом найденные референсы и не более. Их очень жду в интерпретации нашего дизайна :)

2024-08-27 12:22 UTC, gizeasy requested changes

2024-08-27 12:22 UTC, gizeasy commented on src/components/Tag/__stand__/Tag.use.stand.mdx
> +Используйте **Tag**, когда нужно показать свойства объекта и управлять этими свойствами: в контексте классификации, фильтрации или поиска контента по определенным критериям.
`Tag`

2024-08-29 12:47 UTC, gizeasy approved these changes

2024-08-29 14:04 UTC, merged