docs(List): how-to-use
consta-design-system/uikit pull request #3695
Opened 2024-07-03 10:43 UTC by alyonurchick1

closes consta-design-system/uikit#3635

2024-08-27 12:27 UTC, gizeasy requested changes

2024-08-27 12:27 UTC, gizeasy commented on src/components/ListCanary/__stand__/List.use.stand.mdx
> +Компонент **List** предназначен для отображения структурированных данных в виде вертикального списка. Он упрощает представление информации, делает ее более доступной и легко воспринимаемой пользовате
**List** -> `List`

2024-08-27 12:27 UTC, gizeasy commented on src/components/ListCanary/__stand__/List.use.stand.mdx
> +**Пример**. Меню навигации на сайте с подкатегориями и подразделами.
**Пример**. Боковое меню навигации на сайте с подкатегориями и подразделами.

2024-08-27 12:27 UTC, gizeasy commented on src/components/ListCanary/__stand__/List.use.stand.mdx
> +Делайте элементы списка краткими и информативными. Избегайте перегруженности информации, чтобы не отвлекать пользователя.
Избегайте перегруженности информацией

2024-08-27 12:27 UTC, gizeasy commented on src/components/ListCanary/__stand__/List.use.stand.mdx
> +[ContextMenu](##LIBS.LIB.STAND/lib:uikit/stand:components-contextmenu-stable) — компонент для предоставления быстрого доступа к действиям и опциям, которые актуальны в контексте конкретного элемента
**ContextMenu** -> `ContextMenu`

2024-08-29 12:47 UTC, gizeasy approved these changes

2024-08-29 14:04 UTC, merged

2024-09-12 18:49 UTC, alyonurchick1 commented on src/components/ListCanary/__stand__/List.use.stand.mdx
> +Делайте элементы списка краткими и информативными. Избегайте перегруженности информацией, чтобы не отвлекать пользователя.
надо заменить перегруженность на перегрузку