Auto complete click
consta-design-system/uikit pull request #3711
Opened 2024-07-28 16:25 UTC by ZettZet

## Описание изменений
- dropdown скрывается, если выбран элемент из списка
- dropdown не открывается повторно, если выбран элемент из списка
- добавлены тесты на эти сценарии

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2024-08-01 16:08 UTC, gizeasy requested changes

2024-08-01 16:08 UTC, gizeasy commented on src/components/AutoComplete/useAutoComplete.ts
>        setIsOpen.on();
думаю что можно вовсе убрать логику открытия при изменении `searchValue`, кажется прозрачнее всего будет так: если после фильтрации items есть то показываем его, таким образом контроль состоянием можно будет сделать в свойстве searchFunction.

И надо добавить открытие по фокусу

2024-08-09 17:29 UTC, ZettZet commented on src/components/AutoComplete/useAutoComplete.ts
> +      setIsOpen.off();
Но ведь при вводе улицы, дома сразу будут отображены. Это же не fuzzy поиск, а полнотекстовый
Но даже если мы переопределим searchFunction, варианты все равно будут отображаться все, и выбор какого-то из дропдауна всегда приводит к валидному значению, чем и завершает поиск. Я не прав?

2024-08-09 17:33 UTC, ZettZet commented on src/components/AutoComplete/useAutoComplete.ts
>        setIsOpen.on();
Как эту логику запихнуть в `searchFunction` не понятно, она же является простым фильтром
В эффекте это понтяно как выразить:
```ts
useEffect(() => {
  if (filteredOptions.length > 1) {
    setIsOpen.on();
  }
}, [filteredOptions.length]);
```

2024-08-19 07:09 UTC, gizeasy commented on src/components/AutoComplete/useAutoComplete.ts
> +      setIsOpen.off();
я к тому что при клике на улицу я хочу заполнить улицу и дальше вводить адрес не скрывая подсказки.

2024-08-19 07:36 UTC, gizeasy commented on src/components/AutoComplete/useAutoComplete.ts
>        setIsOpen.on();
Я тут совсем по другому решил эту проблему

https://github.com/consta-design-system/uikit/pull/3735

Кажется так лучше всего будет

2024-08-19 08:52 UTC, closed without merging